// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A configuration object describing how Cloud Bigtable should treat traffic
/// from a particular end user application.
public struct AppProfile: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The unique name of the app profile. Values are of the form
  /// `projects/{project}/instances/{instance}/appProfiles/[_a-zA-Z0-9][-_.a-zA-Z0-9]*`.
  public var name: Swift.String = Swift.String()

  /// Strongly validated etag for optimistic concurrency control. Preserve the
  /// value returned from `GetAppProfile` when calling `UpdateAppProfile` to
  /// fail the request if there has been a modification in the mean time. The
  /// `update_mask` of the request need not include `etag` for this protection
  /// to apply.
  /// See [Wikipedia](https://en.wikipedia.org/wiki/HTTP_ETag) and
  /// [RFC 7232](https://tools.ietf.org/html/rfc7232#section-2.3) for more
  /// details.
  public var etag: Swift.String = Swift.String()

  /// Long form description of the use case for this AppProfile.
  public var description: Swift.String = Swift.String()

  /// The routing policy for all read/write requests that use this app profile.
  /// A value must be explicitly set.
  public var routingPolicy: OneOf_RoutingPolicy? = nil

  /// Options for isolating this app profile's traffic from other use cases.
  public var isolation: OneOf_Isolation? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AppProfile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppProfile().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let etag = CodingKeys(stringValue: "etag")
    static let description = CodingKeys(stringValue: "description")
    static let multiClusterRoutingUseAny = CodingKeys(stringValue: "multiClusterRoutingUseAny")
    static let singleClusterRouting = CodingKeys(stringValue: "singleClusterRouting")
    static let priority = CodingKeys(stringValue: "priority")
    static let standardIsolation = CodingKeys(stringValue: "standardIsolation")
    static let dataBoostIsolationReadOnly = CodingKeys(stringValue: "dataBoostIsolationReadOnly")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "etag",
      "description",
      "multiClusterRoutingUseAny",
      "singleClusterRouting",
      "priority",
      "standardIsolation",
      "dataBoostIsolationReadOnly",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }

    var routingPolicy: OneOf_RoutingPolicy? = nil
    let routingPolicyCheckAndSet = {
      if routingPolicy != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'routingPolicy'"))
      }
      routingPolicy = $0
    }
    if let multiClusterRoutingUseAny = try container.decodeIfPresent(
      AppProfile.MultiClusterRoutingUseAny?.self, forKey: .multiClusterRoutingUseAny)
    {
      try routingPolicyCheckAndSet(.multiClusterRoutingUseAny(multiClusterRoutingUseAny))
    }
    if let singleClusterRouting = try container.decodeIfPresent(
      AppProfile.SingleClusterRouting?.self, forKey: .singleClusterRouting)
    {
      try routingPolicyCheckAndSet(.singleClusterRouting(singleClusterRouting))
    }
    self.routingPolicy = routingPolicy

    var isolation: OneOf_Isolation? = nil
    let isolationCheckAndSet = {
      if isolation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'isolation'"))
      }
      isolation = $0
    }
    if let priority = try container.decodeIfPresent(AppProfile.Priority.self, forKey: .priority) {
      try isolationCheckAndSet(.priority(priority))
    }
    if let standardIsolation = try container.decodeIfPresent(
      AppProfile.StandardIsolation?.self, forKey: .standardIsolation)
    {
      try isolationCheckAndSet(.standardIsolation(standardIsolation))
    }
    if let dataBoostIsolationReadOnly = try container.decodeIfPresent(
      AppProfile.DataBoostIsolationReadOnly?.self, forKey: .dataBoostIsolationReadOnly)
    {
      try isolationCheckAndSet(.dataBoostIsolationReadOnly(dataBoostIsolationReadOnly))
    }
    self.isolation = isolation
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.description, forKey: .description)

    if let choice = self.routingPolicy {
      switch choice {
      case .multiClusterRoutingUseAny(let value):
        try container.encode(value, forKey: .multiClusterRoutingUseAny)
      case .singleClusterRouting(let value):
        try container.encode(value, forKey: .singleClusterRouting)
      }
    }

    if let choice = self.isolation {
      switch choice {
      case .priority(let value):
        try container.encode(value, forKey: .priority)
      case .standardIsolation(let value):
        try container.encode(value, forKey: .standardIsolation)
      case .dataBoostIsolationReadOnly(let value):
        try container.encode(value, forKey: .dataBoostIsolationReadOnly)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Read/write requests are routed to the nearest cluster in the instance, and
  /// will fail over to the nearest cluster that is available in the event of
  /// transient errors or delays. Clusters in a region are considered
  /// equidistant. Choosing this option sacrifices read-your-writes consistency
  /// to improve availability.
  public struct MultiClusterRoutingUseAny: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The set of clusters to route to. The order is ignored; clusters will be
    /// tried in order of distance. If left empty, all clusters are eligible.
    public var clusterIds: [Swift.String] = []

    /// Possible algorithms for routing affinity. If enabled, Bigtable will
    /// route between equidistant clusters in a deterministic order rather than
    /// choosing randomly.
    ///
    /// This mechanism gives read-your-writes consistency for *most* requests
    /// under *most* circumstances, without sacrificing availability. Consistency
    /// is *not* guaranteed, as requests might still fail over between clusters
    /// in the event of errors or latency.
    public var affinity: OneOf_Affinity? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MultiClusterRoutingUseAny`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MultiClusterRoutingUseAny().with { $0.clusterIds = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clusterIds = CodingKeys(stringValue: "clusterIds")
      static let rowAffinity = CodingKeys(stringValue: "rowAffinity")

      static let _knownKeys: Set<Swift.String> = [
        "clusterIds",
        "rowAffinity",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .clusterIds) {
        self.clusterIds = value
      }

      var affinity: OneOf_Affinity? = nil
      let affinityCheckAndSet = {
        if affinity != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'affinity'"))
        }
        affinity = $0
      }
      if let rowAffinity = try container.decodeIfPresent(
        AppProfile.MultiClusterRoutingUseAny.RowAffinity?.self, forKey: .rowAffinity)
      {
        try affinityCheckAndSet(.rowAffinity(rowAffinity))
      }
      self.affinity = affinity
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.clusterIds, forKey: .clusterIds)

      if let choice = self.affinity {
        switch choice {
        case .rowAffinity(let value):
          try container.encode(value, forKey: .rowAffinity)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// If enabled, Bigtable will route the request based on the row key of the
    /// request, rather than randomly. Instead, each row key will be assigned
    /// to a cluster, and will stick to that cluster. If clusters are added or
    /// removed, then this may affect which row keys stick to which clusters.
    /// To avoid this, users can use a cluster group to specify which clusters
    /// are to be used. In this case, new clusters that are not a part of the
    /// cluster group will not be routed to, and routing will be unaffected by
    /// the new cluster. Moreover, clusters specified in the cluster group cannot
    /// be deleted unless removed from the cluster group.
    public struct RowAffinity: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `RowAffinity`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = RowAffinity().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let _knownKeys: Set<Swift.String> = []
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.bigtable.admin.v2.AppProfile.MultiClusterRoutingUseAny.RowAffinity"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Possible algorithms for routing affinity. If enabled, Bigtable will
    /// route between equidistant clusters in a deterministic order rather than
    /// choosing randomly.
    ///
    /// This mechanism gives read-your-writes consistency for *most* requests
    /// under *most* circumstances, without sacrificing availability. Consistency
    /// is *not* guaranteed, as requests might still fail over between clusters
    /// in the event of errors or latency.
    public enum OneOf_Affinity: Codable, Equatable, Sendable {
      /// Row affinity sticky routing based on the row key of the request.
      /// Requests that span multiple rows are routed non-deterministically.
      indirect case rowAffinity(AppProfile.MultiClusterRoutingUseAny.RowAffinity?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.AppProfile.MultiClusterRoutingUseAny"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Unconditionally routes all read/write requests to a specific cluster.
  /// This option preserves read-your-writes consistency but does not improve
  /// availability.
  public struct SingleClusterRouting: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The cluster to which read/write requests should be routed.
    public var clusterId: Swift.String = Swift.String()

    /// Whether or not `CheckAndMutateRow` and `ReadModifyWriteRow` requests are
    /// allowed by this app profile. It is unsafe to send these requests to
    /// the same table/row/column in multiple clusters.
    public var allowTransactionalWrites: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SingleClusterRouting`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SingleClusterRouting().with { $0.clusterId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clusterId = CodingKeys(stringValue: "clusterId")
      static let allowTransactionalWrites = CodingKeys(stringValue: "allowTransactionalWrites")

      static let _knownKeys: Set<Swift.String> = [
        "clusterId",
        "allowTransactionalWrites",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterId) {
        self.clusterId = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .allowTransactionalWrites)
      {
        self.allowTransactionalWrites = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.clusterId, forKey: .clusterId)
      try container.encode(self.allowTransactionalWrites, forKey: .allowTransactionalWrites)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.AppProfile.SingleClusterRouting"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Standard options for isolating this app profile's traffic from other use
  /// cases.
  public struct StandardIsolation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The priority of requests sent using this app profile.
    public var priority: AppProfile.Priority = AppProfile.Priority()

    /// Optional. The memory config to use for requests sent using this app
    /// profile.
    public var memoryConfig: AppProfile.StandardIsolation.MemoryConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StandardIsolation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StandardIsolation().with { $0.priority = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let priority = CodingKeys(stringValue: "priority")
      static let memoryConfig = CodingKeys(stringValue: "memoryConfig")

      static let _knownKeys: Set<Swift.String> = [
        "priority",
        "memoryConfig",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(AppProfile.Priority.self, forKey: .priority) {
        self.priority = value
      }
      self.memoryConfig = try container.decodeIfPresent(
        AppProfile.StandardIsolation.MemoryConfig.self, forKey: .memoryConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.priority, forKey: .priority)
      try container.encodeIfPresent(self.memoryConfig, forKey: .memoryConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// If set, eligible single-row requests (currently limited to ReadRows)
    /// using this app profile will be routed to the memory layer. All eligible
    /// writes populate the memory layer. MemoryConfig can only be set if the
    /// AppProfile uses single cluster routing and the configured cluster has a
    /// memory layer enabled.
    public struct MemoryConfig: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `MemoryConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MemoryConfig().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let _knownKeys: Set<Swift.String> = []
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.bigtable.admin.v2.AppProfile.StandardIsolation.MemoryConfig"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.AppProfile.StandardIsolation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Data Boost is a serverless compute capability that lets you run
  /// high-throughput read jobs and queries on your Bigtable data, without
  /// impacting the performance of the clusters that handle your application
  /// traffic. Data Boost supports read-only use cases with single-cluster
  /// routing.
  public struct DataBoostIsolationReadOnly: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The Compute Billing Owner for this Data Boost App Profile.
    public var computeBillingOwner: AppProfile.DataBoostIsolationReadOnly.ComputeBillingOwner? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DataBoostIsolationReadOnly`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DataBoostIsolationReadOnly().with { $0.computeBillingOwner = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let computeBillingOwner = CodingKeys(stringValue: "computeBillingOwner")

      static let _knownKeys: Set<Swift.String> = [
        "computeBillingOwner"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.computeBillingOwner = try container.decodeIfPresent(
        AppProfile.DataBoostIsolationReadOnly.ComputeBillingOwner.self, forKey: .computeBillingOwner
      )
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.computeBillingOwner, forKey: .computeBillingOwner)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Compute Billing Owner specifies how usage should be accounted when using
    /// Data Boost. Compute Billing Owner also configures which Cloud Project is
    /// charged for relevant quota.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ComputeBillingOwner: Codable, Equatable, Sendable {
      /// Unspecified value.
      case unspecified
      /// The host Cloud Project containing the targeted Bigtable Instance /
      /// Table pays for compute.
      case hostPays
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .hostPays: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "COMPUTE_BILLING_OWNER_UNSPECIFIED"
        case .hostPays: return "HOST_PAYS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ComputeBillingOwner/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "COMPUTE_BILLING_OWNER_UNSPECIFIED": self = .unspecified
        case "HOST_PAYS": self = .hostPays
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ComputeBillingOwner/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .hostPays
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("COMPUTE_BILLING_OWNER_UNSPECIFIED")
        case .hostPays: return try container.encode("HOST_PAYS")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.AppProfile.DataBoostIsolationReadOnly"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible priorities for an app profile. Note that higher priority writes
  /// can sometimes queue behind lower priority writes to the same tablet, as
  /// writes must be strictly sequenced in the durability log.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Priority: Codable, Equatable, Sendable {
    /// Default value. Mapped to PRIORITY_HIGH (the legacy behavior) on creation.
    case unspecified
    case low
    case medium
    case high
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .low: return 1
      case .medium: return 2
      case .high: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PRIORITY_UNSPECIFIED"
      case .low: return "PRIORITY_LOW"
      case .medium: return "PRIORITY_MEDIUM"
      case .high: return "PRIORITY_HIGH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Priority/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PRIORITY_UNSPECIFIED": self = .unspecified
      case "PRIORITY_LOW": self = .low
      case "PRIORITY_MEDIUM": self = .medium
      case "PRIORITY_HIGH": self = .high
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Priority/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .low
      case 2: self = .medium
      case 3: self = .high
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PRIORITY_UNSPECIFIED")
      case .low: return try container.encode("PRIORITY_LOW")
      case .medium: return try container.encode("PRIORITY_MEDIUM")
      case .high: return try container.encode("PRIORITY_HIGH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The routing policy for all read/write requests that use this app profile.
  /// A value must be explicitly set.
  public enum OneOf_RoutingPolicy: Codable, Equatable, Sendable {
    /// Use a multi-cluster routing policy.
    indirect case multiClusterRoutingUseAny(AppProfile.MultiClusterRoutingUseAny?)
    /// Use a single-cluster routing policy.
    indirect case singleClusterRouting(AppProfile.SingleClusterRouting?)
  }

  /// Options for isolating this app profile's traffic from other use cases.
  public enum OneOf_Isolation: Codable, Equatable, Sendable {
    /// This field has been deprecated in favor of `standard_isolation.priority`.
    /// If you set this field, `standard_isolation.priority` will be set instead.
    ///
    /// The priority of requests sent using this app profile.
    @available(*, deprecated)
    case priority(AppProfile.Priority)
    /// The standard options used for isolating this app profile's traffic from
    /// other use cases.
    indirect case standardIsolation(AppProfile.StandardIsolation?)
    /// Specifies that this app profile is intended for read-only usage via the
    /// Data Boost feature.
    indirect case dataBoostIsolationReadOnly(AppProfile.DataBoostIsolationReadOnly?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.AppProfile"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
