// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AuthorizedViews represent subsets of a particular Cloud Bigtable table. Users
/// can configure access to each Authorized View independently from the table and
/// use the existing Data APIs to access the subset of data.
public struct AuthorizedView: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of this AuthorizedView.
  /// Values are of the form
  /// `projects/{project}/instances/{instance}/tables/{table}/authorizedViews/{authorized_view}`
  public var name: Swift.String = Swift.String()

  /// The etag for this AuthorizedView.
  /// If this is provided on update, it must match the server's etag. The server
  /// returns ABORTED error on a mismatched etag.
  public var etag: Swift.String = Swift.String()

  /// Set to true to make the AuthorizedView protected against deletion.
  /// The parent Table and containing Instance cannot be deleted if an
  /// AuthorizedView has this bit set.
  public var deletionProtection: Swift.Bool = Swift.Bool()

  /// The type of this AuthorizedView.
  public var authorizedView: OneOf_AuthorizedView? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuthorizedView`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthorizedView().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let subsetView = CodingKeys(stringValue: "subsetView")
    static let etag = CodingKeys(stringValue: "etag")
    static let deletionProtection = CodingKeys(stringValue: "deletionProtection")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "subsetView",
      "etag",
      "deletionProtection",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .deletionProtection) {
      self.deletionProtection = value
    }

    var authorizedView: OneOf_AuthorizedView? = nil
    let authorizedViewCheckAndSet = {
      if authorizedView != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'authorizedView'"))
      }
      authorizedView = $0
    }
    if let subsetView = try container.decodeIfPresent(
      AuthorizedView.SubsetView?.self, forKey: .subsetView)
    {
      try authorizedViewCheckAndSet(.subsetView(subsetView))
    }
    self.authorizedView = authorizedView
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.deletionProtection, forKey: .deletionProtection)

    if let choice = self.authorizedView {
      switch choice {
      case .subsetView(let value):
        try container.encode(value, forKey: .subsetView)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Subsets of a column family that are included in this AuthorizedView.
  public struct FamilySubsets: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Individual exact column qualifiers to be included in the AuthorizedView.
    public var qualifiers: [Foundation.Data] = []

    /// Prefixes for qualifiers to be included in the AuthorizedView. Every
    /// qualifier starting with one of these prefixes is included in the
    /// AuthorizedView. To provide access to all qualifiers, include the empty
    /// string as a prefix
    /// ("").
    public var qualifierPrefixes: [Foundation.Data] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FamilySubsets`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FamilySubsets().with { $0.qualifiers = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let qualifiers = CodingKeys(stringValue: "qualifiers")
      static let qualifierPrefixes = CodingKeys(stringValue: "qualifierPrefixes")

      static let _knownKeys: Set<Swift.String> = [
        "qualifiers",
        "qualifierPrefixes",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Foundation.Data].self, forKey: .qualifiers) {
        self.qualifiers = value
      }
      if let value = try container.decodeIfPresent(
        [Foundation.Data].self, forKey: .qualifierPrefixes)
      {
        self.qualifierPrefixes = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.qualifiers, forKey: .qualifiers)
      try container.encode(self.qualifierPrefixes, forKey: .qualifierPrefixes)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.AuthorizedView.FamilySubsets"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines a simple AuthorizedView that is a subset of the underlying Table.
  public struct SubsetView: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Row prefixes to be included in the AuthorizedView.
    /// To provide access to all rows, include the empty string as a prefix ("").
    public var rowPrefixes: [Foundation.Data] = []

    /// Map from column family name to the columns in this family to be included
    /// in the AuthorizedView.
    public var familySubsets: [Swift.String: AuthorizedView.FamilySubsets] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SubsetView`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SubsetView().with { $0.rowPrefixes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let rowPrefixes = CodingKeys(stringValue: "rowPrefixes")
      static let familySubsets = CodingKeys(stringValue: "familySubsets")

      static let _knownKeys: Set<Swift.String> = [
        "rowPrefixes",
        "familySubsets",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Foundation.Data].self, forKey: .rowPrefixes) {
        self.rowPrefixes = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: AuthorizedView.FamilySubsets].self, forKey: .familySubsets)
      {
        self.familySubsets = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.rowPrefixes, forKey: .rowPrefixes)
      try container.encode(self.familySubsets, forKey: .familySubsets)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.AuthorizedView.SubsetView"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines a subset of an AuthorizedView's fields.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ResponseView: Codable, Equatable, Sendable {
    /// Uses the default view for each method as documented in the request.
    case unspecified
    /// Only populates `name`.
    case nameOnly
    /// Only populates the AuthorizedView's basic metadata. This includes:
    /// name, deletion_protection, etag.
    case basic
    /// Populates every fields.
    case full
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .nameOnly: return 1
      case .basic: return 2
      case .full: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESPONSE_VIEW_UNSPECIFIED"
      case .nameOnly: return "NAME_ONLY"
      case .basic: return "BASIC"
      case .full: return "FULL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResponseView/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESPONSE_VIEW_UNSPECIFIED": self = .unspecified
      case "NAME_ONLY": self = .nameOnly
      case "BASIC": self = .basic
      case "FULL": self = .full
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResponseView/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .nameOnly
      case 2: self = .basic
      case 3: self = .full
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("RESPONSE_VIEW_UNSPECIFIED")
      case .nameOnly: return try container.encode("NAME_ONLY")
      case .basic: return try container.encode("BASIC")
      case .full: return try container.encode("FULL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type of this AuthorizedView.
  public enum OneOf_AuthorizedView: Codable, Equatable, Sendable {
    /// An AuthorizedView permitting access to an explicit subset of a Table.
    indirect case subsetView(AuthorizedView.SubsetView?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.AuthorizedView"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
