// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class BigtableInstanceAdminRetry: BigtableInstanceAdminStub {
    let inner: any BigtableInstanceAdminStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any BigtableInstanceAdminStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createInstance(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Instance {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListInstancesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func updateInstance(
      request: Instance, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Instance {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: Instance, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.Instance
          in
          return try await self.inner.updateInstance(request: r, options: o)
        })
    }

    public func partialUpdateInstance(
      request: PartialUpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PartialUpdateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.partialUpdateInstance(request: r, options: o)
        })
    }

    public func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteInstanceRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteInstance(request: r, options: o)
        })
    }

    public func createCluster(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCluster(request: r, options: o)
        })
    }

    public func getCluster(
      request: GetClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Cluster {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.Cluster
          in
          return try await self.inner.getCluster(request: r, options: o)
        })
    }

    public func listClusters(
      request: ListClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListClustersResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListClustersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListClustersResponse
          in
          return try await self.inner.listClusters(request: r, options: o)
        })
    }

    public func updateCluster(
      request: Cluster, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: Cluster, o: GoogleGax.RequestOptions) async throws -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCluster(request: r, options: o)
        })
    }

    public func partialUpdateCluster(
      request: PartialUpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PartialUpdateClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.partialUpdateCluster(request: r, options: o)
        })
    }

    public func deleteCluster(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteClusterRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteCluster(request: r, options: o)
        })
    }

    public func updateMemoryLayer(
      request: UpdateMemoryLayerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateMemoryLayerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMemoryLayer(request: r, options: o)
        })
    }

    public func listMemoryLayers(
      request: ListMemoryLayersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListMemoryLayersResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMemoryLayersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListMemoryLayersResponse
          in
          return try await self.inner.listMemoryLayers(request: r, options: o)
        })
    }

    public func getMemoryLayer(
      request: GetMemoryLayerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.MemoryLayer {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMemoryLayerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.MemoryLayer
          in
          return try await self.inner.getMemoryLayer(request: r, options: o)
        })
    }

    public func createAppProfile(
      request: CreateAppProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.AppProfile {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAppProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.AppProfile
          in
          return try await self.inner.createAppProfile(request: r, options: o)
        })
    }

    public func getAppProfile(
      request: GetAppProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.AppProfile {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAppProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.AppProfile
          in
          return try await self.inner.getAppProfile(request: r, options: o)
        })
    }

    public func listAppProfiles(
      request: ListAppProfilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListAppProfilesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAppProfilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListAppProfilesResponse
          in
          return try await self.inner.listAppProfiles(request: r, options: o)
        })
    }

    public func updateAppProfile(
      request: UpdateAppProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAppProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAppProfile(request: r, options: o)
        })
    }

    public func deleteAppProfile(
      request: DeleteAppProfileRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteAppProfileRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAppProfile(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listHotTablets(
      request: ListHotTabletsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListHotTabletsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListHotTabletsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListHotTabletsResponse
          in
          return try await self.inner.listHotTablets(request: r, options: o)
        })
    }

    public func createLogicalView(
      request: CreateLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateLogicalViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createLogicalView(request: r, options: o)
        })
    }

    public func getLogicalView(
      request: GetLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.LogicalView {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetLogicalViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.LogicalView
          in
          return try await self.inner.getLogicalView(request: r, options: o)
        })
    }

    public func listLogicalViews(
      request: ListLogicalViewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListLogicalViewsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListLogicalViewsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListLogicalViewsResponse
          in
          return try await self.inner.listLogicalViews(request: r, options: o)
        })
    }

    public func updateLogicalView(
      request: UpdateLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateLogicalViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateLogicalView(request: r, options: o)
        })
    }

    public func deleteLogicalView(
      request: DeleteLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteLogicalViewRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteLogicalView(request: r, options: o)
        })
    }

    public func createMaterializedView(
      request: CreateMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMaterializedViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMaterializedView(request: r, options: o)
        })
    }

    public func getMaterializedView(
      request: GetMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.MaterializedView {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMaterializedViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.MaterializedView
          in
          return try await self.inner.getMaterializedView(request: r, options: o)
        })
    }

    public func listMaterializedViews(
      request: ListMaterializedViewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListMaterializedViewsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMaterializedViewsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudBigtableAdminV2.ListMaterializedViewsResponse
          in
          return try await self.inner.listMaterializedViews(request: r, options: o)
        })
    }

    public func updateMaterializedView(
      request: UpdateMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateMaterializedViewRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMaterializedView(request: r, options: o)
        })
    }

    public func deleteMaterializedView(
      request: DeleteMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMaterializedViewRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteMaterializedView(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
