// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for creating, configuring, and deleting Cloud Bigtable Instances and
/// Clusters. Provides access to the Instance and Cluster schemas only, not the
/// tables' metadata or data stored in those tables.
///
/// @Snippet(path: "BigtableInstanceAdminQuickstart")
public final class BigtableInstanceAdminClient: Clients.BigtableInstanceAdminProtocol, Sendable {
  let inner: any Clients.BigtableInstanceAdminStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `BigtableInstanceAdminClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.BigtableInstanceAdminStub = try Clients.BigtableInstanceAdminTransport(
      options)
    inner = Clients.BigtableInstanceAdminRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.BigtableInstanceAdminLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Create an instance within a project.
  ///
  /// Note that exactly one of Cluster.serve_nodes and
  /// Cluster.cluster_config.cluster_autoscaling_config can be set. If
  /// serve_nodes is set to non-zero, then the cluster is manually scaled. If
  /// cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is
  /// enabled.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CreateInstance")
  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createInstance(request: request, options: options)
  }

  /// Create an instance within a project.
  ///
  /// Note that exactly one of Cluster.serve_nodes and
  /// Cluster.cluster_config.cluster_autoscaling_config can be set. If
  /// serve_nodes is set to non-zero, then the cluster is manually scaled. If
  /// cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is
  /// enabled.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CreateInstance")
  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.createInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets information about an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Lists information about instances in a project.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Updates an instance within a project. This method updates only the display
  /// name and type for an Instance. To update other Instance properties, such as
  /// labels, use PartialUpdateInstance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateInstance")
  public func updateInstance(
    request: Instance, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Instance {
    try await self.inner.updateInstance(request: request, options: options)
  }

  /// Partially updates an instance within a project. This method can modify all
  /// fields of an Instance and is the preferred way to update an Instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_PartialUpdateInstance")
  public func partialUpdateInstance(
    request: PartialUpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.partialUpdateInstance(request: request, options: options)
  }

  /// Partially updates an instance within a project. This method can modify all
  /// fields of an Instance and is the preferred way to update an Instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_PartialUpdateInstance")
  public func partialUpdateInstancePollingUntilDone(
    request: PartialUpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.partialUpdateInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Delete an instance from a project.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_DeleteInstance")
  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteInstance(request: request, options: options)
  }

  /// Creates a cluster within an instance.
  ///
  /// Note that exactly one of Cluster.serve_nodes and
  /// Cluster.cluster_config.cluster_autoscaling_config can be set. If
  /// serve_nodes is set to non-zero, then the cluster is manually scaled. If
  /// cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is
  /// enabled.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CreateCluster")
  public func createCluster(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createCluster(request: request, options: options)
  }

  /// Creates a cluster within an instance.
  ///
  /// Note that exactly one of Cluster.serve_nodes and
  /// Cluster.cluster_config.cluster_autoscaling_config can be set. If
  /// serve_nodes is set to non-zero, then the cluster is manually scaled. If
  /// cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is
  /// enabled.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CreateCluster")
  public func createClusterPollingUntilDone(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.createCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets information about a cluster.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_GetCluster")
  public func getCluster(
    request: GetClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Cluster {
    try await self.inner.getCluster(request: request, options: options)
  }

  /// Lists information about clusters in an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListClusters")
  public func listClusters(
    request: ListClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListClustersResponse {
    try await self.inner.listClusters(request: request, options: options)
  }

  /// Updates a cluster within an instance.
  ///
  /// Note that UpdateCluster does not support updating
  /// cluster_config.cluster_autoscaling_config. In order to update it, you
  /// must use PartialUpdateCluster.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateCluster")
  public func updateCluster(
    request: Cluster, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateCluster(request: request, options: options)
  }

  /// Updates a cluster within an instance.
  ///
  /// Note that UpdateCluster does not support updating
  /// cluster_config.cluster_autoscaling_config. In order to update it, you
  /// must use PartialUpdateCluster.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateCluster")
  public func updateClusterPollingUntilDone(
    request: Cluster, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.updateCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Partially updates a cluster within a project. This method is the preferred
  /// way to update a Cluster.
  ///
  /// To enable and update autoscaling, set
  /// cluster_config.cluster_autoscaling_config. When autoscaling is enabled,
  /// serve_nodes is treated as an OUTPUT_ONLY field, meaning that updates to it
  /// are ignored. Note that an update cannot simultaneously set serve_nodes to
  /// non-zero and cluster_config.cluster_autoscaling_config to non-empty, and
  /// also specify both in the update_mask.
  ///
  /// To disable autoscaling, clear cluster_config.cluster_autoscaling_config,
  /// and explicitly set a serve_node count via the update_mask.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_PartialUpdateCluster")
  public func partialUpdateCluster(
    request: PartialUpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.partialUpdateCluster(request: request, options: options)
  }

  /// Partially updates a cluster within a project. This method is the preferred
  /// way to update a Cluster.
  ///
  /// To enable and update autoscaling, set
  /// cluster_config.cluster_autoscaling_config. When autoscaling is enabled,
  /// serve_nodes is treated as an OUTPUT_ONLY field, meaning that updates to it
  /// are ignored. Note that an update cannot simultaneously set serve_nodes to
  /// non-zero and cluster_config.cluster_autoscaling_config to non-empty, and
  /// also specify both in the update_mask.
  ///
  /// To disable autoscaling, clear cluster_config.cluster_autoscaling_config,
  /// and explicitly set a serve_node count via the update_mask.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_PartialUpdateCluster")
  public func partialUpdateClusterPollingUntilDone(
    request: PartialUpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.partialUpdateCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a cluster from an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_DeleteCluster")
  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteCluster(request: request, options: options)
  }

  /// Updates the memory layer of a cluster.
  ///
  /// To enable the memory layer, set the memory_config.
  /// To disable the memory layer, unset the memory_config.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateMemoryLayer")
  public func updateMemoryLayer(
    request: UpdateMemoryLayerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateMemoryLayer(request: request, options: options)
  }

  /// Updates the memory layer of a cluster.
  ///
  /// To enable the memory layer, set the memory_config.
  /// To disable the memory layer, unset the memory_config.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateMemoryLayer")
  public func updateMemoryLayerPollingUntilDone(
    request: UpdateMemoryLayerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<MemoryLayer> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<MemoryLayer>.State in
      return try op._extractStatus(MemoryLayer.self)
    }
    let rawOp = try await self.updateMemoryLayer(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<MemoryLayer>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about memory layers.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListMemoryLayers")
  public func listMemoryLayers(
    request: ListMemoryLayersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListMemoryLayersResponse {
    try await self.inner.listMemoryLayers(request: request, options: options)
  }

  /// Gets information about the memory layer of a cluster.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_GetMemoryLayer")
  public func getMemoryLayer(
    request: GetMemoryLayerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.MemoryLayer {
    try await self.inner.getMemoryLayer(request: request, options: options)
  }

  /// Creates an app profile within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CreateAppProfile")
  public func createAppProfile(
    request: CreateAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.AppProfile {
    try await self.inner.createAppProfile(request: request, options: options)
  }

  /// Gets information about an app profile.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_GetAppProfile")
  public func getAppProfile(
    request: GetAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.AppProfile {
    try await self.inner.getAppProfile(request: request, options: options)
  }

  /// Lists information about app profiles in an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListAppProfiles")
  public func listAppProfiles(
    request: ListAppProfilesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListAppProfilesResponse {
    try await self.inner.listAppProfiles(request: request, options: options)
  }

  /// Updates an app profile within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateAppProfile")
  public func updateAppProfile(
    request: UpdateAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAppProfile(request: request, options: options)
  }

  /// Updates an app profile within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateAppProfile")
  public func updateAppProfilePollingUntilDone(
    request: UpdateAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppProfile> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AppProfile>.State in
      return try op._extractStatus(AppProfile.self)
    }
    let rawOp = try await self.updateAppProfile(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<AppProfile>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an app profile from an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_DeleteAppProfile")
  public func deleteAppProfile(
    request: DeleteAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAppProfile(request: request, options: options)
  }

  /// Gets the access control policy for an instance resource. Returns an empty
  /// policy if an instance exists but does not have a policy set.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Sets the access control policy on an instance resource. Replaces any
  /// existing policy.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Returns permissions that the caller has on the specified instance resource.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Lists hot tablets in a cluster, within the time range provided. Hot
  /// tablets are ordered based on CPU usage.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListHotTablets")
  public func listHotTablets(
    request: ListHotTabletsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListHotTabletsResponse {
    try await self.inner.listHotTablets(request: request, options: options)
  }

  /// Creates a logical view within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CreateLogicalView")
  public func createLogicalView(
    request: CreateLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createLogicalView(request: request, options: options)
  }

  /// Creates a logical view within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CreateLogicalView")
  public func createLogicalViewPollingUntilDone(
    request: CreateLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LogicalView> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LogicalView>.State in
      return try op._extractStatus(LogicalView.self)
    }
    let rawOp = try await self.createLogicalView(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<LogicalView>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets information about a logical view.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_GetLogicalView")
  public func getLogicalView(
    request: GetLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.LogicalView {
    try await self.inner.getLogicalView(request: request, options: options)
  }

  /// Lists information about logical views in an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListLogicalViews")
  public func listLogicalViews(
    request: ListLogicalViewsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListLogicalViewsResponse {
    try await self.inner.listLogicalViews(request: request, options: options)
  }

  /// Updates a logical view within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateLogicalView")
  public func updateLogicalView(
    request: UpdateLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateLogicalView(request: request, options: options)
  }

  /// Updates a logical view within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateLogicalView")
  public func updateLogicalViewPollingUntilDone(
    request: UpdateLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LogicalView> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<LogicalView>.State in
      return try op._extractStatus(LogicalView.self)
    }
    let rawOp = try await self.updateLogicalView(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<LogicalView>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a logical view from an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_DeleteLogicalView")
  public func deleteLogicalView(
    request: DeleteLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteLogicalView(request: request, options: options)
  }

  /// Creates a materialized view within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CreateMaterializedView")
  public func createMaterializedView(
    request: CreateMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createMaterializedView(request: request, options: options)
  }

  /// Creates a materialized view within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CreateMaterializedView")
  public func createMaterializedViewPollingUntilDone(
    request: CreateMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<MaterializedView> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<MaterializedView>.State in
      return try op._extractStatus(MaterializedView.self)
    }
    let rawOp = try await self.createMaterializedView(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<MaterializedView>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets information about a materialized view.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_GetMaterializedView")
  public func getMaterializedView(
    request: GetMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.MaterializedView {
    try await self.inner.getMaterializedView(request: request, options: options)
  }

  /// Lists information about materialized views in an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListMaterializedViews")
  public func listMaterializedViews(
    request: ListMaterializedViewsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListMaterializedViewsResponse {
    try await self.inner.listMaterializedViews(request: request, options: options)
  }

  /// Updates a materialized view within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateMaterializedView")
  public func updateMaterializedView(
    request: UpdateMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateMaterializedView(request: request, options: options)
  }

  /// Updates a materialized view within an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_UpdateMaterializedView")
  public func updateMaterializedViewPollingUntilDone(
    request: UpdateMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<MaterializedView> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<MaterializedView>.State in
      return try op._extractStatus(MaterializedView.self)
    }
    let rawOp = try await self.updateMaterializedView(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<MaterializedView>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a materialized view from an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_DeleteMaterializedView")
  public func deleteMaterializedView(
    request: DeleteMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteMaterializedView(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `BigtableInstanceAdminClient`.
  ///
  /// To mock `BigtableInstanceAdminClient` change your functions to receive
  /// `some BigtableInstanceAdminProtocol` or `any BigtableInstanceAdminProtocol`
  /// and pass a mock implementation in your tests.
  public protocol BigtableInstanceAdminProtocol: Sendable {
    /// See `BigtableInstanceAdminClient.createInstance`.
    func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.createInstance`.
    func createInstancePollingUntilDone(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `BigtableInstanceAdminClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Instance

    /// See `BigtableInstanceAdminClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListInstancesResponse

    /// See `BigtableInstanceAdminClient.updateInstance`.
    func updateInstance(
      request: Instance, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Instance

    /// See `BigtableInstanceAdminClient.partialUpdateInstance`.
    func partialUpdateInstance(
      request: PartialUpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.partialUpdateInstance`.
    func partialUpdateInstancePollingUntilDone(
      request: PartialUpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `BigtableInstanceAdminClient.deleteInstance`.
    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableInstanceAdminClient.createCluster`.
    func createCluster(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.createCluster`.
    func createClusterPollingUntilDone(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `BigtableInstanceAdminClient.getCluster`.
    func getCluster(
      request: GetClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Cluster

    /// See `BigtableInstanceAdminClient.listClusters`.
    func listClusters(
      request: ListClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListClustersResponse

    /// See `BigtableInstanceAdminClient.updateCluster`.
    func updateCluster(
      request: Cluster, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.updateCluster`.
    func updateClusterPollingUntilDone(
      request: Cluster, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `BigtableInstanceAdminClient.partialUpdateCluster`.
    func partialUpdateCluster(
      request: PartialUpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.partialUpdateCluster`.
    func partialUpdateClusterPollingUntilDone(
      request: PartialUpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `BigtableInstanceAdminClient.deleteCluster`.
    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableInstanceAdminClient.updateMemoryLayer`.
    func updateMemoryLayer(
      request: UpdateMemoryLayerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.updateMemoryLayer`.
    func updateMemoryLayerPollingUntilDone(
      request: UpdateMemoryLayerRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<MemoryLayer>

    /// See `BigtableInstanceAdminClient.listMemoryLayers`.
    func listMemoryLayers(
      request: ListMemoryLayersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListMemoryLayersResponse

    /// See `BigtableInstanceAdminClient.getMemoryLayer`.
    func getMemoryLayer(
      request: GetMemoryLayerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.MemoryLayer

    /// See `BigtableInstanceAdminClient.createAppProfile`.
    func createAppProfile(
      request: CreateAppProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.AppProfile

    /// See `BigtableInstanceAdminClient.getAppProfile`.
    func getAppProfile(
      request: GetAppProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.AppProfile

    /// See `BigtableInstanceAdminClient.listAppProfiles`.
    func listAppProfiles(
      request: ListAppProfilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListAppProfilesResponse

    /// See `BigtableInstanceAdminClient.updateAppProfile`.
    func updateAppProfile(
      request: UpdateAppProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.updateAppProfile`.
    func updateAppProfilePollingUntilDone(
      request: UpdateAppProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AppProfile>

    /// See `BigtableInstanceAdminClient.deleteAppProfile`.
    func deleteAppProfile(
      request: DeleteAppProfileRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableInstanceAdminClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `BigtableInstanceAdminClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `BigtableInstanceAdminClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `BigtableInstanceAdminClient.listHotTablets`.
    func listHotTablets(
      request: ListHotTabletsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListHotTabletsResponse

    /// See `BigtableInstanceAdminClient.createLogicalView`.
    func createLogicalView(
      request: CreateLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.createLogicalView`.
    func createLogicalViewPollingUntilDone(
      request: CreateLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<LogicalView>

    /// See `BigtableInstanceAdminClient.getLogicalView`.
    func getLogicalView(
      request: GetLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.LogicalView

    /// See `BigtableInstanceAdminClient.listLogicalViews`.
    func listLogicalViews(
      request: ListLogicalViewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListLogicalViewsResponse

    /// See `BigtableInstanceAdminClient.updateLogicalView`.
    func updateLogicalView(
      request: UpdateLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.updateLogicalView`.
    func updateLogicalViewPollingUntilDone(
      request: UpdateLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<LogicalView>

    /// See `BigtableInstanceAdminClient.deleteLogicalView`.
    func deleteLogicalView(
      request: DeleteLogicalViewRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableInstanceAdminClient.createMaterializedView`.
    func createMaterializedView(
      request: CreateMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.createMaterializedView`.
    func createMaterializedViewPollingUntilDone(
      request: CreateMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<MaterializedView>

    /// See `BigtableInstanceAdminClient.getMaterializedView`.
    func getMaterializedView(
      request: GetMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.MaterializedView

    /// See `BigtableInstanceAdminClient.listMaterializedViews`.
    func listMaterializedViews(
      request: ListMaterializedViewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListMaterializedViewsResponse

    /// See `BigtableInstanceAdminClient.updateMaterializedView`.
    func updateMaterializedView(
      request: UpdateMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableInstanceAdminClient.updateMaterializedView`.
    func updateMaterializedViewPollingUntilDone(
      request: UpdateMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<MaterializedView>

    /// See `BigtableInstanceAdminClient.deleteMaterializedView`.
    func deleteMaterializedView(
      request: DeleteMaterializedViewRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableInstanceAdminClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `BigtableInstanceAdminClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableInstanceAdminClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.BigtableInstanceAdminProtocol {
  public func createInstance(request: CreateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createInstance(request: request, options: .init())
  }

  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createInstancePollingUntilDone(request: CreateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.createInstancePollingUntilDone(request: request, options: .init())
  }

  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInstancePollingUntilDone(
    parent: Swift.String,
    instanceId: Swift.String,
    instance: Instance?,
    clusters: [Swift.String: Cluster],
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = CreateInstanceRequest().with {
      $0.parent = parent
      $0.instanceId = instanceId
      $0.instance = instance
      $0.clusters = clusters
    }
    return try await self.createInstancePollingUntilDone(request: request)
  }

  public func getInstance(request: GetInstanceRequest) async throws
    -> GoogleCloudBigtableAdminV2.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Instance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getInstance(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.Instance {
    let request = GetInstanceRequest().with {
      $0.name = name
    }
    return try await self.getInstance(request: request)
  }

  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListInstancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listInstances(
    parent: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.ListInstancesResponse {
    let request = ListInstancesRequest().with {
      $0.parent = parent
    }
    return try await self.listInstances(request: request)
  }

  public func updateInstance(request: Instance) async throws -> GoogleCloudBigtableAdminV2.Instance
  {
    try await self.updateInstance(request: request, options: .init())
  }

  public func updateInstance(
    request: Instance, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Instance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func partialUpdateInstance(request: PartialUpdateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.partialUpdateInstance(request: request, options: .init())
  }

  public func partialUpdateInstance(
    request: PartialUpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func partialUpdateInstancePollingUntilDone(request: PartialUpdateInstanceRequest)
    async throws -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.partialUpdateInstancePollingUntilDone(request: request, options: .init())
  }

  public func partialUpdateInstancePollingUntilDone(
    request: PartialUpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func partialUpdateInstancePollingUntilDone(
    instance: Instance?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = PartialUpdateInstanceRequest().with {
      $0.instance = instance
      $0.updateMask = updateMask
    }
    return try await self.partialUpdateInstancePollingUntilDone(request: request)
  }

  public func deleteInstance(request: DeleteInstanceRequest) async throws {
    try await self.deleteInstance(request: request, options: .init())
  }

  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteInstance(
    name: Swift.String,
  ) async throws {
    let request = DeleteInstanceRequest().with {
      $0.name = name
    }
    try await self.deleteInstance(request: request)
  }

  public func createCluster(request: CreateClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createCluster(request: request, options: .init())
  }

  public func createCluster(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createClusterPollingUntilDone(request: CreateClusterRequest) async throws
    -> any GoogleGax.PollableOperation<Cluster>
  {
    try await self.createClusterPollingUntilDone(request: request, options: .init())
  }

  public func createClusterPollingUntilDone(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createClusterPollingUntilDone(
    parent: Swift.String,
    clusterId: Swift.String,
    cluster: Cluster?,
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let request = CreateClusterRequest().with {
      $0.parent = parent
      $0.clusterId = clusterId
      $0.cluster = cluster
    }
    return try await self.createClusterPollingUntilDone(request: request)
  }

  public func getCluster(request: GetClusterRequest) async throws
    -> GoogleCloudBigtableAdminV2.Cluster
  {
    try await self.getCluster(request: request, options: .init())
  }

  public func getCluster(
    request: GetClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Cluster {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.Cluster {
    let request = GetClusterRequest().with {
      $0.name = name
    }
    return try await self.getCluster(request: request)
  }

  public func listClusters(request: ListClustersRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListClustersResponse
  {
    try await self.listClusters(request: request, options: .init())
  }

  public func listClusters(
    request: ListClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListClustersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listClusters(
    parent: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.ListClustersResponse {
    let request = ListClustersRequest().with {
      $0.parent = parent
    }
    return try await self.listClusters(request: request)
  }

  public func updateCluster(request: Cluster) async throws -> GoogleLongRunning.Operation {
    try await self.updateCluster(request: request, options: .init())
  }

  public func updateCluster(
    request: Cluster, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateClusterPollingUntilDone(request: Cluster) async throws -> any GoogleGax
    .PollableOperation<Cluster>
  {
    try await self.updateClusterPollingUntilDone(request: request, options: .init())
  }

  public func updateClusterPollingUntilDone(
    request: Cluster, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func partialUpdateCluster(request: PartialUpdateClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.partialUpdateCluster(request: request, options: .init())
  }

  public func partialUpdateCluster(
    request: PartialUpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func partialUpdateClusterPollingUntilDone(request: PartialUpdateClusterRequest)
    async throws -> any GoogleGax.PollableOperation<Cluster>
  {
    try await self.partialUpdateClusterPollingUntilDone(request: request, options: .init())
  }

  public func partialUpdateClusterPollingUntilDone(
    request: PartialUpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func partialUpdateClusterPollingUntilDone(
    cluster: Cluster?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let request = PartialUpdateClusterRequest().with {
      $0.cluster = cluster
      $0.updateMask = updateMask
    }
    return try await self.partialUpdateClusterPollingUntilDone(request: request)
  }

  public func deleteCluster(request: DeleteClusterRequest) async throws {
    try await self.deleteCluster(request: request, options: .init())
  }

  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteCluster(
    name: Swift.String,
  ) async throws {
    let request = DeleteClusterRequest().with {
      $0.name = name
    }
    try await self.deleteCluster(request: request)
  }

  public func updateMemoryLayer(request: UpdateMemoryLayerRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateMemoryLayer(request: request, options: .init())
  }

  public func updateMemoryLayer(
    request: UpdateMemoryLayerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateMemoryLayerPollingUntilDone(request: UpdateMemoryLayerRequest) async throws
    -> any GoogleGax.PollableOperation<MemoryLayer>
  {
    try await self.updateMemoryLayerPollingUntilDone(request: request, options: .init())
  }

  public func updateMemoryLayerPollingUntilDone(
    request: UpdateMemoryLayerRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<MemoryLayer> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<MemoryLayer>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateMemoryLayerPollingUntilDone(
    memoryLayer: MemoryLayer?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<MemoryLayer> {
    let request = UpdateMemoryLayerRequest().with {
      $0.memoryLayer = memoryLayer
      $0.updateMask = updateMask
    }
    return try await self.updateMemoryLayerPollingUntilDone(request: request)
  }

  public func listMemoryLayers(request: ListMemoryLayersRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListMemoryLayersResponse
  {
    try await self.listMemoryLayers(request: request, options: .init())
  }

  public func listMemoryLayers(
    request: ListMemoryLayersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListMemoryLayersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listMemoryLayersByItems(
    request: ListMemoryLayersRequest
  ) -> some AsyncSequence<MemoryLayer, Swift.Error> & Sendable {
    self.listMemoryLayersByItems(request: request, options: .init())
  }

  /// Lists information about memory layers.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListMemoryLayers")
  public func listMemoryLayersByItems(
    request: ListMemoryLayersRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<MemoryLayer, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudBigtableAdminV2.ListMemoryLayersResponse in
      var request = request
      request.pageToken = token
      return try await self.listMemoryLayers(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listMemoryLayersByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<MemoryLayer, Swift.Error> & Sendable {
    let request = ListMemoryLayersRequest().with {
      $0.parent = parent
    }
    return self.listMemoryLayersByItems(request: request)
  }

  public func getMemoryLayer(request: GetMemoryLayerRequest) async throws
    -> GoogleCloudBigtableAdminV2.MemoryLayer
  {
    try await self.getMemoryLayer(request: request, options: .init())
  }

  public func getMemoryLayer(
    request: GetMemoryLayerRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.MemoryLayer {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getMemoryLayer(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.MemoryLayer {
    let request = GetMemoryLayerRequest().with {
      $0.name = name
    }
    return try await self.getMemoryLayer(request: request)
  }

  public func createAppProfile(request: CreateAppProfileRequest) async throws
    -> GoogleCloudBigtableAdminV2.AppProfile
  {
    try await self.createAppProfile(request: request, options: .init())
  }

  public func createAppProfile(
    request: CreateAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.AppProfile {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAppProfile(
    parent: Swift.String,
    appProfileId: Swift.String,
    appProfile: AppProfile?,
  ) async throws -> GoogleCloudBigtableAdminV2.AppProfile {
    let request = CreateAppProfileRequest().with {
      $0.parent = parent
      $0.appProfileId = appProfileId
      $0.appProfile = appProfile
    }
    return try await self.createAppProfile(request: request)
  }

  public func getAppProfile(request: GetAppProfileRequest) async throws
    -> GoogleCloudBigtableAdminV2.AppProfile
  {
    try await self.getAppProfile(request: request, options: .init())
  }

  public func getAppProfile(
    request: GetAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.AppProfile {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAppProfile(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.AppProfile {
    let request = GetAppProfileRequest().with {
      $0.name = name
    }
    return try await self.getAppProfile(request: request)
  }

  public func listAppProfiles(request: ListAppProfilesRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListAppProfilesResponse
  {
    try await self.listAppProfiles(request: request, options: .init())
  }

  public func listAppProfiles(
    request: ListAppProfilesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListAppProfilesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAppProfilesByItems(
    request: ListAppProfilesRequest
  ) -> some AsyncSequence<AppProfile, Swift.Error> & Sendable {
    self.listAppProfilesByItems(request: request, options: .init())
  }

  /// Lists information about app profiles in an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListAppProfiles")
  public func listAppProfilesByItems(
    request: ListAppProfilesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<AppProfile, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudBigtableAdminV2.ListAppProfilesResponse in
      var request = request
      request.pageToken = token
      return try await self.listAppProfiles(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAppProfilesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<AppProfile, Swift.Error> & Sendable {
    let request = ListAppProfilesRequest().with {
      $0.parent = parent
    }
    return self.listAppProfilesByItems(request: request)
  }

  public func updateAppProfile(request: UpdateAppProfileRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAppProfile(request: request, options: .init())
  }

  public func updateAppProfile(
    request: UpdateAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAppProfilePollingUntilDone(request: UpdateAppProfileRequest) async throws
    -> any GoogleGax.PollableOperation<AppProfile>
  {
    try await self.updateAppProfilePollingUntilDone(request: request, options: .init())
  }

  public func updateAppProfilePollingUntilDone(
    request: UpdateAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppProfile> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<AppProfile>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAppProfilePollingUntilDone(
    appProfile: AppProfile?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<AppProfile> {
    let request = UpdateAppProfileRequest().with {
      $0.appProfile = appProfile
      $0.updateMask = updateMask
    }
    return try await self.updateAppProfilePollingUntilDone(request: request)
  }

  public func deleteAppProfile(request: DeleteAppProfileRequest) async throws {
    try await self.deleteAppProfile(request: request, options: .init())
  }

  public func deleteAppProfile(
    request: DeleteAppProfileRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAppProfile(
    name: Swift.String,
  ) async throws {
    let request = DeleteAppProfileRequest().with {
      $0.name = name
    }
    try await self.deleteAppProfile(request: request)
  }

  public func deleteAppProfile(
    name: Swift.String,
    ignoreWarnings: Swift.Bool,
  ) async throws {
    let request = DeleteAppProfileRequest().with {
      $0.name = name
      $0.ignoreWarnings = ignoreWarnings
    }
    try await self.deleteAppProfile(request: request)
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(
    resource: Swift.String,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.GetIamPolicyRequest().with {
      $0.resource = resource
    }
    return try await self.getIamPolicy(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(
    resource: Swift.String,
    policy: GoogleIAMV1.Policy?,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.SetIamPolicyRequest().with {
      $0.resource = resource
      $0.policy = policy
    }
    return try await self.setIamPolicy(request: request)
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(
    resource: Swift.String,
    permissions: [Swift.String],
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    let request = GoogleIAMV1.TestIamPermissionsRequest().with {
      $0.resource = resource
      $0.permissions = permissions
    }
    return try await self.testIamPermissions(request: request)
  }

  public func listHotTablets(request: ListHotTabletsRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListHotTabletsResponse
  {
    try await self.listHotTablets(request: request, options: .init())
  }

  public func listHotTablets(
    request: ListHotTabletsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListHotTabletsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listHotTabletsByItems(
    request: ListHotTabletsRequest
  ) -> some AsyncSequence<HotTablet, Swift.Error> & Sendable {
    self.listHotTabletsByItems(request: request, options: .init())
  }

  /// Lists hot tablets in a cluster, within the time range provided. Hot
  /// tablets are ordered based on CPU usage.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListHotTablets")
  public func listHotTabletsByItems(
    request: ListHotTabletsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<HotTablet, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudBigtableAdminV2.ListHotTabletsResponse in
      var request = request
      request.pageToken = token
      return try await self.listHotTablets(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listHotTabletsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<HotTablet, Swift.Error> & Sendable {
    let request = ListHotTabletsRequest().with {
      $0.parent = parent
    }
    return self.listHotTabletsByItems(request: request)
  }

  public func createLogicalView(request: CreateLogicalViewRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createLogicalView(request: request, options: .init())
  }

  public func createLogicalView(
    request: CreateLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createLogicalViewPollingUntilDone(request: CreateLogicalViewRequest) async throws
    -> any GoogleGax.PollableOperation<LogicalView>
  {
    try await self.createLogicalViewPollingUntilDone(request: request, options: .init())
  }

  public func createLogicalViewPollingUntilDone(
    request: CreateLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LogicalView> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<LogicalView>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createLogicalViewPollingUntilDone(
    parent: Swift.String,
    logicalView: LogicalView?,
    logicalViewId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<LogicalView> {
    let request = CreateLogicalViewRequest().with {
      $0.parent = parent
      $0.logicalView = logicalView
      $0.logicalViewId = logicalViewId
    }
    return try await self.createLogicalViewPollingUntilDone(request: request)
  }

  public func getLogicalView(request: GetLogicalViewRequest) async throws
    -> GoogleCloudBigtableAdminV2.LogicalView
  {
    try await self.getLogicalView(request: request, options: .init())
  }

  public func getLogicalView(
    request: GetLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.LogicalView {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getLogicalView(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.LogicalView {
    let request = GetLogicalViewRequest().with {
      $0.name = name
    }
    return try await self.getLogicalView(request: request)
  }

  public func listLogicalViews(request: ListLogicalViewsRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListLogicalViewsResponse
  {
    try await self.listLogicalViews(request: request, options: .init())
  }

  public func listLogicalViews(
    request: ListLogicalViewsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListLogicalViewsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLogicalViewsByItems(
    request: ListLogicalViewsRequest
  ) -> some AsyncSequence<LogicalView, Swift.Error> & Sendable {
    self.listLogicalViewsByItems(request: request, options: .init())
  }

  /// Lists information about logical views in an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListLogicalViews")
  public func listLogicalViewsByItems(
    request: ListLogicalViewsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<LogicalView, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudBigtableAdminV2.ListLogicalViewsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLogicalViews(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLogicalViewsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<LogicalView, Swift.Error> & Sendable {
    let request = ListLogicalViewsRequest().with {
      $0.parent = parent
    }
    return self.listLogicalViewsByItems(request: request)
  }

  public func updateLogicalView(request: UpdateLogicalViewRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateLogicalView(request: request, options: .init())
  }

  public func updateLogicalView(
    request: UpdateLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateLogicalViewPollingUntilDone(request: UpdateLogicalViewRequest) async throws
    -> any GoogleGax.PollableOperation<LogicalView>
  {
    try await self.updateLogicalViewPollingUntilDone(request: request, options: .init())
  }

  public func updateLogicalViewPollingUntilDone(
    request: UpdateLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<LogicalView> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<LogicalView>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateLogicalViewPollingUntilDone(
    logicalView: LogicalView?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<LogicalView> {
    let request = UpdateLogicalViewRequest().with {
      $0.logicalView = logicalView
      $0.updateMask = updateMask
    }
    return try await self.updateLogicalViewPollingUntilDone(request: request)
  }

  public func deleteLogicalView(request: DeleteLogicalViewRequest) async throws {
    try await self.deleteLogicalView(request: request, options: .init())
  }

  public func deleteLogicalView(
    request: DeleteLogicalViewRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteLogicalView(
    name: Swift.String,
  ) async throws {
    let request = DeleteLogicalViewRequest().with {
      $0.name = name
    }
    try await self.deleteLogicalView(request: request)
  }

  public func createMaterializedView(request: CreateMaterializedViewRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createMaterializedView(request: request, options: .init())
  }

  public func createMaterializedView(
    request: CreateMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createMaterializedViewPollingUntilDone(request: CreateMaterializedViewRequest)
    async throws -> any GoogleGax.PollableOperation<MaterializedView>
  {
    try await self.createMaterializedViewPollingUntilDone(request: request, options: .init())
  }

  public func createMaterializedViewPollingUntilDone(
    request: CreateMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<MaterializedView> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<MaterializedView>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createMaterializedViewPollingUntilDone(
    parent: Swift.String,
    materializedView: MaterializedView?,
    materializedViewId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<MaterializedView> {
    let request = CreateMaterializedViewRequest().with {
      $0.parent = parent
      $0.materializedView = materializedView
      $0.materializedViewId = materializedViewId
    }
    return try await self.createMaterializedViewPollingUntilDone(request: request)
  }

  public func getMaterializedView(request: GetMaterializedViewRequest) async throws
    -> GoogleCloudBigtableAdminV2.MaterializedView
  {
    try await self.getMaterializedView(request: request, options: .init())
  }

  public func getMaterializedView(
    request: GetMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.MaterializedView {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getMaterializedView(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.MaterializedView {
    let request = GetMaterializedViewRequest().with {
      $0.name = name
    }
    return try await self.getMaterializedView(request: request)
  }

  public func listMaterializedViews(request: ListMaterializedViewsRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListMaterializedViewsResponse
  {
    try await self.listMaterializedViews(request: request, options: .init())
  }

  public func listMaterializedViews(
    request: ListMaterializedViewsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListMaterializedViewsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listMaterializedViewsByItems(
    request: ListMaterializedViewsRequest
  ) -> some AsyncSequence<MaterializedView, Swift.Error> & Sendable {
    self.listMaterializedViewsByItems(request: request, options: .init())
  }

  /// Lists information about materialized views in an instance.
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListMaterializedViews")
  public func listMaterializedViewsByItems(
    request: ListMaterializedViewsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<MaterializedView, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudBigtableAdminV2.ListMaterializedViewsResponse in
      var request = request
      request.pageToken = token
      return try await self.listMaterializedViews(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listMaterializedViewsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<MaterializedView, Swift.Error> & Sendable {
    let request = ListMaterializedViewsRequest().with {
      $0.parent = parent
    }
    return self.listMaterializedViewsByItems(request: request)
  }

  public func updateMaterializedView(request: UpdateMaterializedViewRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateMaterializedView(request: request, options: .init())
  }

  public func updateMaterializedView(
    request: UpdateMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateMaterializedViewPollingUntilDone(request: UpdateMaterializedViewRequest)
    async throws -> any GoogleGax.PollableOperation<MaterializedView>
  {
    try await self.updateMaterializedViewPollingUntilDone(request: request, options: .init())
  }

  public func updateMaterializedViewPollingUntilDone(
    request: UpdateMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<MaterializedView> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<MaterializedView>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateMaterializedViewPollingUntilDone(
    materializedView: MaterializedView?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<MaterializedView> {
    let request = UpdateMaterializedViewRequest().with {
      $0.materializedView = materializedView
      $0.updateMask = updateMask
    }
    return try await self.updateMaterializedViewPollingUntilDone(request: request)
  }

  public func deleteMaterializedView(request: DeleteMaterializedViewRequest) async throws {
    try await self.deleteMaterializedView(request: request, options: .init())
  }

  public func deleteMaterializedView(
    request: DeleteMaterializedViewRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteMaterializedView(
    name: Swift.String,
  ) async throws {
    let request = DeleteMaterializedViewRequest().with {
      $0.name = name
    }
    try await self.deleteMaterializedView(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableInstanceAdmin_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
