// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for creating, configuring, and deleting Cloud Bigtable tables.
///
///
/// Provides access to the table schemas only, not the data stored within
/// the tables.
///
/// @Snippet(path: "BigtableTableAdminQuickstart")
public final class BigtableTableAdminClient: Clients.BigtableTableAdminProtocol, Sendable {
  let inner: any Clients.BigtableTableAdminStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `BigtableTableAdminClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.BigtableTableAdminStub = try Clients.BigtableTableAdminTransport(options)
    inner = Clients.BigtableTableAdminRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.BigtableTableAdminLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new table in the specified instance.
  /// The table can be created with a full set of initial column families,
  /// specified in the request.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CreateTable")
  public func createTable(
    request: CreateTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Table {
    try await self.inner.createTable(request: request, options: options)
  }

  /// Creates a new table from the specified snapshot. The target table must
  /// not exist. The snapshot and the table must be in the same instance.
  ///
  /// Note: This is a private alpha release of Cloud Bigtable snapshots. This
  /// feature is not currently available to most Cloud Bigtable customers. This
  /// feature might be changed in backward-incompatible ways and is not
  /// recommended for production use. It is not subject to any SLA or deprecation
  /// policy.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CreateTableFromSnapshot")
  public func createTableFromSnapshot(
    request: CreateTableFromSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createTableFromSnapshot(request: request, options: options)
  }

  /// Creates a new table from the specified snapshot. The target table must
  /// not exist. The snapshot and the table must be in the same instance.
  ///
  /// Note: This is a private alpha release of Cloud Bigtable snapshots. This
  /// feature is not currently available to most Cloud Bigtable customers. This
  /// feature might be changed in backward-incompatible ways and is not
  /// recommended for production use. It is not subject to any SLA or deprecation
  /// policy.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CreateTableFromSnapshot")
  public func createTableFromSnapshot(
    withPolling: CreateTableFromSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Table>.State in
      return try op._extractStatus(Table.self)
    }
    let rawOp = try await self.createTableFromSnapshot(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Table>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all tables served from a specified instance.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListTables")
  public func listTables(
    request: ListTablesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListTablesResponse {
    try await self.inner.listTables(request: request, options: options)
  }

  /// Gets metadata information about the specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_GetTable")
  public func getTable(
    request: GetTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Table {
    try await self.inner.getTable(request: request, options: options)
  }

  /// Updates a specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_UpdateTable")
  public func updateTable(
    request: UpdateTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateTable(request: request, options: options)
  }

  /// Updates a specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_UpdateTable")
  public func updateTable(
    withPolling: UpdateTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Table>.State in
      return try op._extractStatus(Table.self)
    }
    let rawOp = try await self.updateTable(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Table>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Permanently deletes a specified table and all of its data.
  ///
  /// @Snippet(path: "BigtableTableAdmin_DeleteTable")
  public func deleteTable(
    request: DeleteTableRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteTable(request: request, options: options)
  }

  /// Restores a specified table which was accidentally deleted.
  ///
  /// @Snippet(path: "BigtableTableAdmin_UndeleteTable")
  public func undeleteTable(
    request: UndeleteTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.undeleteTable(request: request, options: options)
  }

  /// Restores a specified table which was accidentally deleted.
  ///
  /// @Snippet(path: "BigtableTableAdmin_UndeleteTable")
  public func undeleteTable(
    withPolling: UndeleteTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Table>.State in
      return try op._extractStatus(Table.self)
    }
    let rawOp = try await self.undeleteTable(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Table>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a new AuthorizedView in a table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CreateAuthorizedView")
  public func createAuthorizedView(
    request: CreateAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAuthorizedView(request: request, options: options)
  }

  /// Creates a new AuthorizedView in a table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CreateAuthorizedView")
  public func createAuthorizedView(
    withPolling: CreateAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuthorizedView> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AuthorizedView>.State in
      return try op._extractStatus(AuthorizedView.self)
    }
    let rawOp = try await self.createAuthorizedView(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuthorizedView>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all AuthorizedViews from a specific table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListAuthorizedViews")
  public func listAuthorizedViews(
    request: ListAuthorizedViewsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListAuthorizedViewsResponse {
    try await self.inner.listAuthorizedViews(request: request, options: options)
  }

  /// Gets information from a specified AuthorizedView.
  ///
  /// @Snippet(path: "BigtableTableAdmin_GetAuthorizedView")
  public func getAuthorizedView(
    request: GetAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.AuthorizedView {
    try await self.inner.getAuthorizedView(request: request, options: options)
  }

  /// Updates an AuthorizedView in a table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_UpdateAuthorizedView")
  public func updateAuthorizedView(
    request: UpdateAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAuthorizedView(request: request, options: options)
  }

  /// Updates an AuthorizedView in a table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_UpdateAuthorizedView")
  public func updateAuthorizedView(
    withPolling: UpdateAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuthorizedView> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AuthorizedView>.State in
      return try op._extractStatus(AuthorizedView.self)
    }
    let rawOp = try await self.updateAuthorizedView(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuthorizedView>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Permanently deletes a specified AuthorizedView.
  ///
  /// @Snippet(path: "BigtableTableAdmin_DeleteAuthorizedView")
  public func deleteAuthorizedView(
    request: DeleteAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAuthorizedView(request: request, options: options)
  }

  /// Performs a series of column family modifications on the specified table.
  /// Either all or none of the modifications will occur before this method
  /// returns, but data requests received prior to that point may see a table
  /// where only some modifications have taken effect.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ModifyColumnFamilies")
  public func modifyColumnFamilies(
    request: ModifyColumnFamiliesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Table {
    try await self.inner.modifyColumnFamilies(request: request, options: options)
  }

  /// Permanently drop/delete a row range from a specified table. The request can
  /// specify whether to delete all rows in a table, or only those that match a
  /// particular prefix.
  ///
  /// @Snippet(path: "BigtableTableAdmin_DropRowRange")
  public func dropRowRange(
    request: DropRowRangeRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.dropRowRange(request: request, options: options)
  }

  /// Generates a consistency token for a Table, which can be used in
  /// CheckConsistency to check whether mutations to the table that finished
  /// before this call started have been replicated. The tokens will be available
  /// for 90 days.
  ///
  /// @Snippet(path: "BigtableTableAdmin_GenerateConsistencyToken")
  public func generateConsistencyToken(
    request: GenerateConsistencyTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.GenerateConsistencyTokenResponse {
    try await self.inner.generateConsistencyToken(request: request, options: options)
  }

  /// Checks replication consistency based on a consistency token, that is, if
  /// replication has caught up based on the conditions specified in the token
  /// and the check request.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CheckConsistency")
  public func checkConsistency(
    request: CheckConsistencyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.CheckConsistencyResponse {
    try await self.inner.checkConsistency(request: request, options: options)
  }

  /// Creates a new snapshot in the specified cluster from the specified
  /// source table. The cluster and the table must be in the same instance.
  ///
  /// Note: This is a private alpha release of Cloud Bigtable snapshots. This
  /// feature is not currently available to most Cloud Bigtable customers. This
  /// feature might be changed in backward-incompatible ways and is not
  /// recommended for production use. It is not subject to any SLA or deprecation
  /// policy.
  ///
  /// @Snippet(path: "BigtableTableAdmin_SnapshotTable")
  public func snapshotTable(
    request: SnapshotTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.snapshotTable(request: request, options: options)
  }

  /// Creates a new snapshot in the specified cluster from the specified
  /// source table. The cluster and the table must be in the same instance.
  ///
  /// Note: This is a private alpha release of Cloud Bigtable snapshots. This
  /// feature is not currently available to most Cloud Bigtable customers. This
  /// feature might be changed in backward-incompatible ways and is not
  /// recommended for production use. It is not subject to any SLA or deprecation
  /// policy.
  ///
  /// @Snippet(path: "BigtableTableAdmin_SnapshotTable")
  public func snapshotTable(
    withPolling: SnapshotTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Snapshot> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Snapshot>.State
      in
      return try op._extractStatus(Snapshot.self)
    }
    let rawOp = try await self.snapshotTable(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Snapshot>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets metadata information about the specified snapshot.
  ///
  /// Note: This is a private alpha release of Cloud Bigtable snapshots. This
  /// feature is not currently available to most Cloud Bigtable customers. This
  /// feature might be changed in backward-incompatible ways and is not
  /// recommended for production use. It is not subject to any SLA or deprecation
  /// policy.
  ///
  /// @Snippet(path: "BigtableTableAdmin_GetSnapshot")
  public func getSnapshot(
    request: GetSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Snapshot {
    try await self.inner.getSnapshot(request: request, options: options)
  }

  /// Lists all snapshots associated with the specified cluster.
  ///
  /// Note: This is a private alpha release of Cloud Bigtable snapshots. This
  /// feature is not currently available to most Cloud Bigtable customers. This
  /// feature might be changed in backward-incompatible ways and is not
  /// recommended for production use. It is not subject to any SLA or deprecation
  /// policy.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListSnapshots")
  public func listSnapshots(
    request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListSnapshotsResponse {
    try await self.inner.listSnapshots(request: request, options: options)
  }

  /// Permanently deletes the specified snapshot.
  ///
  /// Note: This is a private alpha release of Cloud Bigtable snapshots. This
  /// feature is not currently available to most Cloud Bigtable customers. This
  /// feature might be changed in backward-incompatible ways and is not
  /// recommended for production use. It is not subject to any SLA or deprecation
  /// policy.
  ///
  /// @Snippet(path: "BigtableTableAdmin_DeleteSnapshot")
  public func deleteSnapshot(
    request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteSnapshot(request: request, options: options)
  }

  /// Starts creating a new Cloud Bigtable Backup.  The returned backup
  /// [long-running operation][google.longrunning.Operation] can be used to
  /// track creation of the backup. The
  /// [metadata][google.longrunning.Operation.metadata] field type is
  /// [CreateBackupMetadata][google.bigtable.admin.v2.CreateBackupMetadata]. The
  /// [response][google.longrunning.Operation.response] field type is
  /// [Backup][google.bigtable.admin.v2.Backup], if successful. Cancelling the
  /// returned operation will stop the creation and delete the backup.
  ///
  /// [google.bigtable.admin.v2.Backup]: <doc:Backup>
  /// [google.bigtable.admin.v2.CreateBackupMetadata]: <doc:CreateBackupMetadata>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  /// [google.longrunning.Operation.metadata]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/metadata
  /// [google.longrunning.Operation.response]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/OneOf_Result/response(_:)
  ///
  /// @Snippet(path: "BigtableTableAdmin_CreateBackup")
  public func createBackup(
    request: CreateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createBackup(request: request, options: options)
  }

  /// Starts creating a new Cloud Bigtable Backup.  The returned backup
  /// [long-running operation][google.longrunning.Operation] can be used to
  /// track creation of the backup. The
  /// [metadata][google.longrunning.Operation.metadata] field type is
  /// [CreateBackupMetadata][google.bigtable.admin.v2.CreateBackupMetadata]. The
  /// [response][google.longrunning.Operation.response] field type is
  /// [Backup][google.bigtable.admin.v2.Backup], if successful. Cancelling the
  /// returned operation will stop the creation and delete the backup.
  ///
  /// [google.bigtable.admin.v2.Backup]: <doc:Backup>
  /// [google.bigtable.admin.v2.CreateBackupMetadata]: <doc:CreateBackupMetadata>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  /// [google.longrunning.Operation.metadata]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/metadata
  /// [google.longrunning.Operation.response]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/OneOf_Result/response(_:)
  ///
  /// @Snippet(path: "BigtableTableAdmin_CreateBackup")
  public func createBackup(
    withPolling: CreateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      return try op._extractStatus(Backup.self)
    }
    let rawOp = try await self.createBackup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets metadata on a pending or completed Cloud Bigtable Backup.
  ///
  /// @Snippet(path: "BigtableTableAdmin_GetBackup")
  public func getBackup(
    request: GetBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Backup {
    try await self.inner.getBackup(request: request, options: options)
  }

  /// Updates a pending or completed Cloud Bigtable Backup.
  ///
  /// @Snippet(path: "BigtableTableAdmin_UpdateBackup")
  public func updateBackup(
    request: UpdateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Backup {
    try await self.inner.updateBackup(request: request, options: options)
  }

  /// Deletes a pending or completed Cloud Bigtable backup.
  ///
  /// @Snippet(path: "BigtableTableAdmin_DeleteBackup")
  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteBackup(request: request, options: options)
  }

  /// Lists Cloud Bigtable backups. Returns both completed and pending
  /// backups.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListBackups")
  public func listBackups(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListBackupsResponse {
    try await self.inner.listBackups(request: request, options: options)
  }

  /// Create a new table by restoring from a completed backup.  The
  /// returned table [long-running operation][google.longrunning.Operation] can
  /// be used to track the progress of the operation, and to cancel it.  The
  /// [metadata][google.longrunning.Operation.metadata] field type is
  /// [RestoreTableMetadata][google.bigtable.admin.v2.RestoreTableMetadata].  The
  /// [response][google.longrunning.Operation.response] type is
  /// [Table][google.bigtable.admin.v2.Table], if successful.
  ///
  /// [google.bigtable.admin.v2.RestoreTableMetadata]: <doc:RestoreTableMetadata>
  /// [google.bigtable.admin.v2.Table]: <doc:Table>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  /// [google.longrunning.Operation.metadata]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/metadata
  /// [google.longrunning.Operation.response]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/OneOf_Result/response(_:)
  ///
  /// @Snippet(path: "BigtableTableAdmin_RestoreTable")
  public func restoreTable(
    request: RestoreTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.restoreTable(request: request, options: options)
  }

  /// Create a new table by restoring from a completed backup.  The
  /// returned table [long-running operation][google.longrunning.Operation] can
  /// be used to track the progress of the operation, and to cancel it.  The
  /// [metadata][google.longrunning.Operation.metadata] field type is
  /// [RestoreTableMetadata][google.bigtable.admin.v2.RestoreTableMetadata].  The
  /// [response][google.longrunning.Operation.response] type is
  /// [Table][google.bigtable.admin.v2.Table], if successful.
  ///
  /// [google.bigtable.admin.v2.RestoreTableMetadata]: <doc:RestoreTableMetadata>
  /// [google.bigtable.admin.v2.Table]: <doc:Table>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  /// [google.longrunning.Operation.metadata]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/metadata
  /// [google.longrunning.Operation.response]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/OneOf_Result/response(_:)
  ///
  /// @Snippet(path: "BigtableTableAdmin_RestoreTable")
  public func restoreTable(
    withPolling: RestoreTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Table>.State in
      return try op._extractStatus(Table.self)
    }
    let rawOp = try await self.restoreTable(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Table>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Copy a Cloud Bigtable backup to a new backup in the destination cluster
  /// located in the destination instance and project.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CopyBackup")
  public func copyBackup(
    request: CopyBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.copyBackup(request: request, options: options)
  }

  /// Copy a Cloud Bigtable backup to a new backup in the destination cluster
  /// located in the destination instance and project.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CopyBackup")
  public func copyBackup(
    withPolling: CopyBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      return try op._extractStatus(Backup.self)
    }
    let rawOp = try await self.copyBackup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets the access control policy for a Bigtable resource.
  /// Returns an empty policy if the resource exists but does not have a policy
  /// set.
  ///
  /// @Snippet(path: "BigtableTableAdmin_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Sets the access control policy on a Bigtable resource.
  /// Replaces any existing policy.
  ///
  /// @Snippet(path: "BigtableTableAdmin_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Returns permissions that the caller has on the specified Bigtable
  /// resource.
  ///
  /// @Snippet(path: "BigtableTableAdmin_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Creates a new schema bundle in the specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CreateSchemaBundle")
  public func createSchemaBundle(
    request: CreateSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createSchemaBundle(request: request, options: options)
  }

  /// Creates a new schema bundle in the specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_CreateSchemaBundle")
  public func createSchemaBundle(
    withPolling: CreateSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<SchemaBundle> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<SchemaBundle>.State in
      return try op._extractStatus(SchemaBundle.self)
    }
    let rawOp = try await self.createSchemaBundle(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<SchemaBundle>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a schema bundle in the specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_UpdateSchemaBundle")
  public func updateSchemaBundle(
    request: UpdateSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateSchemaBundle(request: request, options: options)
  }

  /// Updates a schema bundle in the specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_UpdateSchemaBundle")
  public func updateSchemaBundle(
    withPolling: UpdateSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<SchemaBundle> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<SchemaBundle>.State in
      return try op._extractStatus(SchemaBundle.self)
    }
    let rawOp = try await self.updateSchemaBundle(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<SchemaBundle>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets metadata information about the specified schema bundle.
  ///
  /// @Snippet(path: "BigtableTableAdmin_GetSchemaBundle")
  public func getSchemaBundle(
    request: GetSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.SchemaBundle {
    try await self.inner.getSchemaBundle(request: request, options: options)
  }

  /// Lists all schema bundles associated with the specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListSchemaBundles")
  public func listSchemaBundles(
    request: ListSchemaBundlesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListSchemaBundlesResponse {
    try await self.inner.listSchemaBundles(request: request, options: options)
  }

  /// Deletes a schema bundle in the specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_DeleteSchemaBundle")
  public func deleteSchemaBundle(
    request: DeleteSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteSchemaBundle(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableTableAdmin_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableTableAdmin_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableTableAdmin_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `BigtableTableAdminClient`.
  ///
  /// To mock `BigtableTableAdminClient` change your functions to receive
  /// `some BigtableTableAdminProtocol` or `any BigtableTableAdminProtocol`
  /// and pass a mock implementation in your tests.
  public protocol BigtableTableAdminProtocol: Sendable {
    /// See `BigtableTableAdminClient.createTableFromSnapshot`.
    func createTableFromSnapshot(withPolling: CreateTableFromSnapshotRequest) async throws
      -> any GoogleGax.PollableOperation<Table>

    /// See `BigtableTableAdminClient.createTableFromSnapshot`.
    func createTableFromSnapshot(
      parent: Swift.String,
      tableId: Swift.String,
      sourceSnapshot: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Table>

    /// See `BigtableTableAdminClient.updateTable`.
    func updateTable(withPolling: UpdateTableRequest) async throws -> any GoogleGax
      .PollableOperation<Table>

    /// See `BigtableTableAdminClient.updateTable`.
    func updateTable(
      table: Table?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Table>

    /// See `BigtableTableAdminClient.undeleteTable`.
    func undeleteTable(withPolling: UndeleteTableRequest) async throws -> any GoogleGax
      .PollableOperation<Table>

    /// See `BigtableTableAdminClient.undeleteTable`.
    func undeleteTable(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Table>

    /// See `BigtableTableAdminClient.createAuthorizedView`.
    func createAuthorizedView(withPolling: CreateAuthorizedViewRequest) async throws
      -> any GoogleGax.PollableOperation<AuthorizedView>

    /// See `BigtableTableAdminClient.createAuthorizedView`.
    func createAuthorizedView(
      parent: Swift.String,
      authorizedView: AuthorizedView?,
      authorizedViewId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<AuthorizedView>

    /// See `BigtableTableAdminClient.updateAuthorizedView`.
    func updateAuthorizedView(withPolling: UpdateAuthorizedViewRequest) async throws
      -> any GoogleGax.PollableOperation<AuthorizedView>

    /// See `BigtableTableAdminClient.updateAuthorizedView`.
    func updateAuthorizedView(
      authorizedView: AuthorizedView?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<AuthorizedView>

    /// See `BigtableTableAdminClient.snapshotTable`.
    func snapshotTable(withPolling: SnapshotTableRequest) async throws -> any GoogleGax
      .PollableOperation<Snapshot>

    /// See `BigtableTableAdminClient.snapshotTable`.
    func snapshotTable(
      name: Swift.String,
      cluster: Swift.String,
      snapshotId: Swift.String,
      description: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Snapshot>

    /// See `BigtableTableAdminClient.createBackup`.
    func createBackup(withPolling: CreateBackupRequest) async throws -> any GoogleGax
      .PollableOperation<Backup>

    /// See `BigtableTableAdminClient.createBackup`.
    func createBackup(
      parent: Swift.String,
      backupId: Swift.String,
      backup: Backup?,
    ) async throws -> any GoogleGax.PollableOperation<Backup>

    /// See `BigtableTableAdminClient.restoreTable`.
    func restoreTable(withPolling: RestoreTableRequest) async throws -> any GoogleGax
      .PollableOperation<Table>

    /// See `BigtableTableAdminClient.copyBackup`.
    func copyBackup(withPolling: CopyBackupRequest) async throws -> any GoogleGax.PollableOperation<
      Backup
    >

    /// See `BigtableTableAdminClient.copyBackup`.
    func copyBackup(
      parent: Swift.String,
      backupId: Swift.String,
      sourceBackup: Swift.String,
      expireTime: GoogleWKT.Timestamp?,
    ) async throws -> any GoogleGax.PollableOperation<Backup>

    /// See `BigtableTableAdminClient.createSchemaBundle`.
    func createSchemaBundle(withPolling: CreateSchemaBundleRequest) async throws -> any GoogleGax
      .PollableOperation<SchemaBundle>

    /// See `BigtableTableAdminClient.createSchemaBundle`.
    func createSchemaBundle(
      parent: Swift.String,
      schemaBundleId: Swift.String,
      schemaBundle: SchemaBundle?,
    ) async throws -> any GoogleGax.PollableOperation<SchemaBundle>

    /// See `BigtableTableAdminClient.updateSchemaBundle`.
    func updateSchemaBundle(withPolling: UpdateSchemaBundleRequest) async throws -> any GoogleGax
      .PollableOperation<SchemaBundle>

    /// See `BigtableTableAdminClient.updateSchemaBundle`.
    func updateSchemaBundle(
      schemaBundle: SchemaBundle?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<SchemaBundle>

    /// See `BigtableTableAdminClient.createTable`.
    func createTable(
      request: CreateTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Table

    /// See `BigtableTableAdminClient.createTableFromSnapshot`.
    func createTableFromSnapshot(
      request: CreateTableFromSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.createTableFromSnapshot`.
    func createTableFromSnapshot(
      withPolling: CreateTableFromSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Table>

    /// See `BigtableTableAdminClient.listTables`.
    func listTables(
      request: ListTablesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListTablesResponse

    /// See `BigtableTableAdminClient.getTable`.
    func getTable(
      request: GetTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Table

    /// See `BigtableTableAdminClient.updateTable`.
    func updateTable(
      request: UpdateTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.updateTable`.
    func updateTable(
      withPolling: UpdateTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Table>

    /// See `BigtableTableAdminClient.deleteTable`.
    func deleteTable(
      request: DeleteTableRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableTableAdminClient.undeleteTable`.
    func undeleteTable(
      request: UndeleteTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.undeleteTable`.
    func undeleteTable(
      withPolling: UndeleteTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Table>

    /// See `BigtableTableAdminClient.createAuthorizedView`.
    func createAuthorizedView(
      request: CreateAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.createAuthorizedView`.
    func createAuthorizedView(
      withPolling: CreateAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AuthorizedView>

    /// See `BigtableTableAdminClient.listAuthorizedViews`.
    func listAuthorizedViews(
      request: ListAuthorizedViewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListAuthorizedViewsResponse

    /// See `BigtableTableAdminClient.getAuthorizedView`.
    func getAuthorizedView(
      request: GetAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.AuthorizedView

    /// See `BigtableTableAdminClient.updateAuthorizedView`.
    func updateAuthorizedView(
      request: UpdateAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.updateAuthorizedView`.
    func updateAuthorizedView(
      withPolling: UpdateAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AuthorizedView>

    /// See `BigtableTableAdminClient.deleteAuthorizedView`.
    func deleteAuthorizedView(
      request: DeleteAuthorizedViewRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableTableAdminClient.modifyColumnFamilies`.
    func modifyColumnFamilies(
      request: ModifyColumnFamiliesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Table

    /// See `BigtableTableAdminClient.dropRowRange`.
    func dropRowRange(
      request: DropRowRangeRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableTableAdminClient.generateConsistencyToken`.
    func generateConsistencyToken(
      request: GenerateConsistencyTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.GenerateConsistencyTokenResponse

    /// See `BigtableTableAdminClient.checkConsistency`.
    func checkConsistency(
      request: CheckConsistencyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.CheckConsistencyResponse

    /// See `BigtableTableAdminClient.snapshotTable`.
    func snapshotTable(
      request: SnapshotTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.snapshotTable`.
    func snapshotTable(
      withPolling: SnapshotTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Snapshot>

    /// See `BigtableTableAdminClient.getSnapshot`.
    func getSnapshot(
      request: GetSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Snapshot

    /// See `BigtableTableAdminClient.listSnapshots`.
    func listSnapshots(
      request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListSnapshotsResponse

    /// See `BigtableTableAdminClient.deleteSnapshot`.
    func deleteSnapshot(
      request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableTableAdminClient.createBackup`.
    func createBackup(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.createBackup`.
    func createBackup(
      withPolling: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Backup>

    /// See `BigtableTableAdminClient.getBackup`.
    func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Backup

    /// See `BigtableTableAdminClient.updateBackup`.
    func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.Backup

    /// See `BigtableTableAdminClient.deleteBackup`.
    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableTableAdminClient.listBackups`.
    func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListBackupsResponse

    /// See `BigtableTableAdminClient.restoreTable`.
    func restoreTable(
      request: RestoreTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.restoreTable`.
    func restoreTable(
      withPolling: RestoreTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Table>

    /// See `BigtableTableAdminClient.copyBackup`.
    func copyBackup(
      request: CopyBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.copyBackup`.
    func copyBackup(
      withPolling: CopyBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Backup>

    /// See `BigtableTableAdminClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `BigtableTableAdminClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `BigtableTableAdminClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `BigtableTableAdminClient.createSchemaBundle`.
    func createSchemaBundle(
      request: CreateSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.createSchemaBundle`.
    func createSchemaBundle(
      withPolling: CreateSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<SchemaBundle>

    /// See `BigtableTableAdminClient.updateSchemaBundle`.
    func updateSchemaBundle(
      request: UpdateSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BigtableTableAdminClient.updateSchemaBundle`.
    func updateSchemaBundle(
      withPolling: UpdateSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<SchemaBundle>

    /// See `BigtableTableAdminClient.getSchemaBundle`.
    func getSchemaBundle(
      request: GetSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.SchemaBundle

    /// See `BigtableTableAdminClient.listSchemaBundles`.
    func listSchemaBundles(
      request: ListSchemaBundlesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBigtableAdminV2.ListSchemaBundlesResponse

    /// See `BigtableTableAdminClient.deleteSchemaBundle`.
    func deleteSchemaBundle(
      request: DeleteSchemaBundleRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableTableAdminClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `BigtableTableAdminClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `BigtableTableAdminClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.BigtableTableAdminProtocol {
  public func createTable(request: CreateTableRequest) async throws
    -> GoogleCloudBigtableAdminV2.Table
  {
    try await self.createTable(request: request, options: .init())
  }

  public func createTable(
    request: CreateTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Table {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createTable(
    parent: Swift.String,
    tableId: Swift.String,
    table: Table?,
  ) async throws -> GoogleCloudBigtableAdminV2.Table {
    let request = CreateTableRequest().with {
      $0.parent = parent
      $0.tableId = tableId
      $0.table = table
    }
    return try await self.createTable(request: request)
  }

  public func createTableFromSnapshot(request: CreateTableFromSnapshotRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createTableFromSnapshot(request: request, options: .init())
  }

  public func createTableFromSnapshot(
    request: CreateTableFromSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createTableFromSnapshot(withPolling: CreateTableFromSnapshotRequest) async throws
    -> any GoogleGax.PollableOperation<Table>
  {
    try await self.createTableFromSnapshot(withPolling: withPolling, options: .init())
  }

  public func createTableFromSnapshot(
    withPolling: CreateTableFromSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Table>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createTableFromSnapshot(
    parent: Swift.String,
    tableId: Swift.String,
    sourceSnapshot: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let request = CreateTableFromSnapshotRequest().with {
      $0.parent = parent
      $0.tableId = tableId
      $0.sourceSnapshot = sourceSnapshot
    }
    return try await self.createTableFromSnapshot(withPolling: request)
  }

  public func listTables(request: ListTablesRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListTablesResponse
  {
    try await self.listTables(request: request, options: .init())
  }

  public func listTables(
    request: ListTablesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListTablesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listTables(
    byItem: ListTablesRequest
  ) -> any AsyncSequence<Table, Swift.Error> {
    self.listTables(byItem: byItem, options: .init())
  }

  /// Lists all tables served from a specified instance.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListTables")
  public func listTables(
    byItem: ListTablesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Table, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudBigtableAdminV2.ListTablesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTables(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTables(
    parent: Swift.String,
  ) -> any AsyncSequence<Table, Swift.Error> {
    let request = ListTablesRequest().with {
      $0.parent = parent
    }
    return self.listTables(byItem: request)
  }

  public func getTable(request: GetTableRequest) async throws -> GoogleCloudBigtableAdminV2.Table {
    try await self.getTable(request: request, options: .init())
  }

  public func getTable(
    request: GetTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Table {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getTable(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.Table {
    let request = GetTableRequest().with {
      $0.name = name
    }
    return try await self.getTable(request: request)
  }

  public func updateTable(request: UpdateTableRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateTable(request: request, options: .init())
  }

  public func updateTable(
    request: UpdateTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateTable(withPolling: UpdateTableRequest) async throws -> any GoogleGax
    .PollableOperation<Table>
  {
    try await self.updateTable(withPolling: withPolling, options: .init())
  }

  public func updateTable(
    withPolling: UpdateTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Table>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateTable(
    table: Table?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let request = UpdateTableRequest().with {
      $0.table = table
      $0.updateMask = updateMask
    }
    return try await self.updateTable(withPolling: request)
  }

  public func deleteTable(request: DeleteTableRequest) async throws {
    try await self.deleteTable(request: request, options: .init())
  }

  public func deleteTable(
    request: DeleteTableRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteTable(
    name: Swift.String,
  ) async throws {
    let request = DeleteTableRequest().with {
      $0.name = name
    }
    try await self.deleteTable(request: request)
  }

  public func undeleteTable(request: UndeleteTableRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.undeleteTable(request: request, options: .init())
  }

  public func undeleteTable(
    request: UndeleteTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func undeleteTable(withPolling: UndeleteTableRequest) async throws -> any GoogleGax
    .PollableOperation<Table>
  {
    try await self.undeleteTable(withPolling: withPolling, options: .init())
  }

  public func undeleteTable(
    withPolling: UndeleteTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Table>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func undeleteTable(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let request = UndeleteTableRequest().with {
      $0.name = name
    }
    return try await self.undeleteTable(withPolling: request)
  }

  public func createAuthorizedView(request: CreateAuthorizedViewRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAuthorizedView(request: request, options: .init())
  }

  public func createAuthorizedView(
    request: CreateAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAuthorizedView(withPolling: CreateAuthorizedViewRequest) async throws
    -> any GoogleGax.PollableOperation<AuthorizedView>
  {
    try await self.createAuthorizedView(withPolling: withPolling, options: .init())
  }

  public func createAuthorizedView(
    withPolling: CreateAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuthorizedView> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuthorizedView>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAuthorizedView(
    parent: Swift.String,
    authorizedView: AuthorizedView?,
    authorizedViewId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<AuthorizedView> {
    let request = CreateAuthorizedViewRequest().with {
      $0.parent = parent
      $0.authorizedView = authorizedView
      $0.authorizedViewId = authorizedViewId
    }
    return try await self.createAuthorizedView(withPolling: request)
  }

  public func listAuthorizedViews(request: ListAuthorizedViewsRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListAuthorizedViewsResponse
  {
    try await self.listAuthorizedViews(request: request, options: .init())
  }

  public func listAuthorizedViews(
    request: ListAuthorizedViewsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListAuthorizedViewsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAuthorizedViews(
    byItem: ListAuthorizedViewsRequest
  ) -> any AsyncSequence<AuthorizedView, Swift.Error> {
    self.listAuthorizedViews(byItem: byItem, options: .init())
  }

  /// Lists all AuthorizedViews from a specific table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListAuthorizedViews")
  public func listAuthorizedViews(
    byItem: ListAuthorizedViewsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AuthorizedView, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudBigtableAdminV2.ListAuthorizedViewsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listAuthorizedViews(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAuthorizedViews(
    parent: Swift.String,
  ) -> any AsyncSequence<AuthorizedView, Swift.Error> {
    let request = ListAuthorizedViewsRequest().with {
      $0.parent = parent
    }
    return self.listAuthorizedViews(byItem: request)
  }

  public func getAuthorizedView(request: GetAuthorizedViewRequest) async throws
    -> GoogleCloudBigtableAdminV2.AuthorizedView
  {
    try await self.getAuthorizedView(request: request, options: .init())
  }

  public func getAuthorizedView(
    request: GetAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.AuthorizedView {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAuthorizedView(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.AuthorizedView {
    let request = GetAuthorizedViewRequest().with {
      $0.name = name
    }
    return try await self.getAuthorizedView(request: request)
  }

  public func updateAuthorizedView(request: UpdateAuthorizedViewRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAuthorizedView(request: request, options: .init())
  }

  public func updateAuthorizedView(
    request: UpdateAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAuthorizedView(withPolling: UpdateAuthorizedViewRequest) async throws
    -> any GoogleGax.PollableOperation<AuthorizedView>
  {
    try await self.updateAuthorizedView(withPolling: withPolling, options: .init())
  }

  public func updateAuthorizedView(
    withPolling: UpdateAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AuthorizedView> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AuthorizedView>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAuthorizedView(
    authorizedView: AuthorizedView?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<AuthorizedView> {
    let request = UpdateAuthorizedViewRequest().with {
      $0.authorizedView = authorizedView
      $0.updateMask = updateMask
    }
    return try await self.updateAuthorizedView(withPolling: request)
  }

  public func deleteAuthorizedView(request: DeleteAuthorizedViewRequest) async throws {
    try await self.deleteAuthorizedView(request: request, options: .init())
  }

  public func deleteAuthorizedView(
    request: DeleteAuthorizedViewRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAuthorizedView(
    name: Swift.String,
  ) async throws {
    let request = DeleteAuthorizedViewRequest().with {
      $0.name = name
    }
    try await self.deleteAuthorizedView(request: request)
  }

  public func modifyColumnFamilies(request: ModifyColumnFamiliesRequest) async throws
    -> GoogleCloudBigtableAdminV2.Table
  {
    try await self.modifyColumnFamilies(request: request, options: .init())
  }

  public func modifyColumnFamilies(
    request: ModifyColumnFamiliesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Table {
    throw GoogleGax.RequestError.unimplemented
  }

  public func modifyColumnFamilies(
    name: Swift.String,
    modifications: [ModifyColumnFamiliesRequest.Modification],
  ) async throws -> GoogleCloudBigtableAdminV2.Table {
    let request = ModifyColumnFamiliesRequest().with {
      $0.name = name
      $0.modifications = modifications
    }
    return try await self.modifyColumnFamilies(request: request)
  }

  public func dropRowRange(request: DropRowRangeRequest) async throws {
    try await self.dropRowRange(request: request, options: .init())
  }

  public func dropRowRange(
    request: DropRowRangeRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func generateConsistencyToken(request: GenerateConsistencyTokenRequest) async throws
    -> GoogleCloudBigtableAdminV2.GenerateConsistencyTokenResponse
  {
    try await self.generateConsistencyToken(request: request, options: .init())
  }

  public func generateConsistencyToken(
    request: GenerateConsistencyTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.GenerateConsistencyTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func generateConsistencyToken(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.GenerateConsistencyTokenResponse {
    let request = GenerateConsistencyTokenRequest().with {
      $0.name = name
    }
    return try await self.generateConsistencyToken(request: request)
  }

  public func checkConsistency(request: CheckConsistencyRequest) async throws
    -> GoogleCloudBigtableAdminV2.CheckConsistencyResponse
  {
    try await self.checkConsistency(request: request, options: .init())
  }

  public func checkConsistency(
    request: CheckConsistencyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.CheckConsistencyResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func checkConsistency(
    name: Swift.String,
    consistencyToken: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.CheckConsistencyResponse {
    let request = CheckConsistencyRequest().with {
      $0.name = name
      $0.consistencyToken = consistencyToken
    }
    return try await self.checkConsistency(request: request)
  }

  public func snapshotTable(request: SnapshotTableRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.snapshotTable(request: request, options: .init())
  }

  public func snapshotTable(
    request: SnapshotTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func snapshotTable(withPolling: SnapshotTableRequest) async throws -> any GoogleGax
    .PollableOperation<Snapshot>
  {
    try await self.snapshotTable(withPolling: withPolling, options: .init())
  }

  public func snapshotTable(
    withPolling: SnapshotTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Snapshot> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Snapshot>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func snapshotTable(
    name: Swift.String,
    cluster: Swift.String,
    snapshotId: Swift.String,
    description: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Snapshot> {
    let request = SnapshotTableRequest().with {
      $0.name = name
      $0.cluster = cluster
      $0.snapshotId = snapshotId
      $0.description = description
    }
    return try await self.snapshotTable(withPolling: request)
  }

  public func getSnapshot(request: GetSnapshotRequest) async throws
    -> GoogleCloudBigtableAdminV2.Snapshot
  {
    try await self.getSnapshot(request: request, options: .init())
  }

  public func getSnapshot(
    request: GetSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Snapshot {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getSnapshot(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.Snapshot {
    let request = GetSnapshotRequest().with {
      $0.name = name
    }
    return try await self.getSnapshot(request: request)
  }

  public func listSnapshots(request: ListSnapshotsRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListSnapshotsResponse
  {
    try await self.listSnapshots(request: request, options: .init())
  }

  public func listSnapshots(
    request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListSnapshotsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listSnapshots(
    byItem: ListSnapshotsRequest
  ) -> any AsyncSequence<Snapshot, Swift.Error> {
    self.listSnapshots(byItem: byItem, options: .init())
  }

  /// Lists all snapshots associated with the specified cluster.
  ///
  /// Note: This is a private alpha release of Cloud Bigtable snapshots. This
  /// feature is not currently available to most Cloud Bigtable customers. This
  /// feature might be changed in backward-incompatible ways and is not
  /// recommended for production use. It is not subject to any SLA or deprecation
  /// policy.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListSnapshots")
  public func listSnapshots(
    byItem: ListSnapshotsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Snapshot, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudBigtableAdminV2.ListSnapshotsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSnapshots(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSnapshots(
    parent: Swift.String,
  ) -> any AsyncSequence<Snapshot, Swift.Error> {
    let request = ListSnapshotsRequest().with {
      $0.parent = parent
    }
    return self.listSnapshots(byItem: request)
  }

  public func deleteSnapshot(request: DeleteSnapshotRequest) async throws {
    try await self.deleteSnapshot(request: request, options: .init())
  }

  public func deleteSnapshot(
    request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteSnapshot(
    name: Swift.String,
  ) async throws {
    let request = DeleteSnapshotRequest().with {
      $0.name = name
    }
    try await self.deleteSnapshot(request: request)
  }

  public func createBackup(request: CreateBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createBackup(request: request, options: .init())
  }

  public func createBackup(
    request: CreateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createBackup(withPolling: CreateBackupRequest) async throws -> any GoogleGax
    .PollableOperation<Backup>
  {
    try await self.createBackup(withPolling: withPolling, options: .init())
  }

  public func createBackup(
    withPolling: CreateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createBackup(
    parent: Swift.String,
    backupId: Swift.String,
    backup: Backup?,
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let request = CreateBackupRequest().with {
      $0.parent = parent
      $0.backupId = backupId
      $0.backup = backup
    }
    return try await self.createBackup(withPolling: request)
  }

  public func getBackup(request: GetBackupRequest) async throws -> GoogleCloudBigtableAdminV2.Backup
  {
    try await self.getBackup(request: request, options: .init())
  }

  public func getBackup(
    request: GetBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Backup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getBackup(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.Backup {
    let request = GetBackupRequest().with {
      $0.name = name
    }
    return try await self.getBackup(request: request)
  }

  public func updateBackup(request: UpdateBackupRequest) async throws
    -> GoogleCloudBigtableAdminV2.Backup
  {
    try await self.updateBackup(request: request, options: .init())
  }

  public func updateBackup(
    request: UpdateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.Backup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateBackup(
    backup: Backup?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleCloudBigtableAdminV2.Backup {
    let request = UpdateBackupRequest().with {
      $0.backup = backup
      $0.updateMask = updateMask
    }
    return try await self.updateBackup(request: request)
  }

  public func deleteBackup(request: DeleteBackupRequest) async throws {
    try await self.deleteBackup(request: request, options: .init())
  }

  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteBackup(
    name: Swift.String,
  ) async throws {
    let request = DeleteBackupRequest().with {
      $0.name = name
    }
    try await self.deleteBackup(request: request)
  }

  public func listBackups(request: ListBackupsRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListBackupsResponse
  {
    try await self.listBackups(request: request, options: .init())
  }

  public func listBackups(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListBackupsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listBackups(
    byItem: ListBackupsRequest
  ) -> any AsyncSequence<Backup, Swift.Error> {
    self.listBackups(byItem: byItem, options: .init())
  }

  /// Lists Cloud Bigtable backups. Returns both completed and pending
  /// backups.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListBackups")
  public func listBackups(
    byItem: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Backup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudBigtableAdminV2.ListBackupsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listBackups(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackups(
    parent: Swift.String,
  ) -> any AsyncSequence<Backup, Swift.Error> {
    let request = ListBackupsRequest().with {
      $0.parent = parent
    }
    return self.listBackups(byItem: request)
  }

  public func restoreTable(request: RestoreTableRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.restoreTable(request: request, options: .init())
  }

  public func restoreTable(
    request: RestoreTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func restoreTable(withPolling: RestoreTableRequest) async throws -> any GoogleGax
    .PollableOperation<Table>
  {
    try await self.restoreTable(withPolling: withPolling, options: .init())
  }

  public func restoreTable(
    withPolling: RestoreTableRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Table> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Table>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func copyBackup(request: CopyBackupRequest) async throws -> GoogleLongRunning.Operation {
    try await self.copyBackup(request: request, options: .init())
  }

  public func copyBackup(
    request: CopyBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func copyBackup(withPolling: CopyBackupRequest) async throws -> any GoogleGax
    .PollableOperation<Backup>
  {
    try await self.copyBackup(withPolling: withPolling, options: .init())
  }

  public func copyBackup(
    withPolling: CopyBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func copyBackup(
    parent: Swift.String,
    backupId: Swift.String,
    sourceBackup: Swift.String,
    expireTime: GoogleWKT.Timestamp?,
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let request = CopyBackupRequest().with {
      $0.parent = parent
      $0.backupId = backupId
      $0.sourceBackup = sourceBackup
      $0.expireTime = expireTime
    }
    return try await self.copyBackup(withPolling: request)
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(
    resource: Swift.String,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.GetIamPolicyRequest().with {
      $0.resource = resource
    }
    return try await self.getIamPolicy(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(
    resource: Swift.String,
    policy: GoogleIAMV1.Policy?,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.SetIamPolicyRequest().with {
      $0.resource = resource
      $0.policy = policy
    }
    return try await self.setIamPolicy(request: request)
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(
    resource: Swift.String,
    permissions: [Swift.String],
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    let request = GoogleIAMV1.TestIamPermissionsRequest().with {
      $0.resource = resource
      $0.permissions = permissions
    }
    return try await self.testIamPermissions(request: request)
  }

  public func createSchemaBundle(request: CreateSchemaBundleRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createSchemaBundle(request: request, options: .init())
  }

  public func createSchemaBundle(
    request: CreateSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createSchemaBundle(withPolling: CreateSchemaBundleRequest) async throws
    -> any GoogleGax.PollableOperation<SchemaBundle>
  {
    try await self.createSchemaBundle(withPolling: withPolling, options: .init())
  }

  public func createSchemaBundle(
    withPolling: CreateSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<SchemaBundle> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<SchemaBundle>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createSchemaBundle(
    parent: Swift.String,
    schemaBundleId: Swift.String,
    schemaBundle: SchemaBundle?,
  ) async throws -> any GoogleGax.PollableOperation<SchemaBundle> {
    let request = CreateSchemaBundleRequest().with {
      $0.parent = parent
      $0.schemaBundleId = schemaBundleId
      $0.schemaBundle = schemaBundle
    }
    return try await self.createSchemaBundle(withPolling: request)
  }

  public func updateSchemaBundle(request: UpdateSchemaBundleRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateSchemaBundle(request: request, options: .init())
  }

  public func updateSchemaBundle(
    request: UpdateSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateSchemaBundle(withPolling: UpdateSchemaBundleRequest) async throws
    -> any GoogleGax.PollableOperation<SchemaBundle>
  {
    try await self.updateSchemaBundle(withPolling: withPolling, options: .init())
  }

  public func updateSchemaBundle(
    withPolling: UpdateSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<SchemaBundle> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<SchemaBundle>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateSchemaBundle(
    schemaBundle: SchemaBundle?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<SchemaBundle> {
    let request = UpdateSchemaBundleRequest().with {
      $0.schemaBundle = schemaBundle
      $0.updateMask = updateMask
    }
    return try await self.updateSchemaBundle(withPolling: request)
  }

  public func getSchemaBundle(request: GetSchemaBundleRequest) async throws
    -> GoogleCloudBigtableAdminV2.SchemaBundle
  {
    try await self.getSchemaBundle(request: request, options: .init())
  }

  public func getSchemaBundle(
    request: GetSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.SchemaBundle {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getSchemaBundle(
    name: Swift.String,
  ) async throws -> GoogleCloudBigtableAdminV2.SchemaBundle {
    let request = GetSchemaBundleRequest().with {
      $0.name = name
    }
    return try await self.getSchemaBundle(request: request)
  }

  public func listSchemaBundles(request: ListSchemaBundlesRequest) async throws
    -> GoogleCloudBigtableAdminV2.ListSchemaBundlesResponse
  {
    try await self.listSchemaBundles(request: request, options: .init())
  }

  public func listSchemaBundles(
    request: ListSchemaBundlesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBigtableAdminV2.ListSchemaBundlesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listSchemaBundles(
    byItem: ListSchemaBundlesRequest
  ) -> any AsyncSequence<SchemaBundle, Swift.Error> {
    self.listSchemaBundles(byItem: byItem, options: .init())
  }

  /// Lists all schema bundles associated with the specified table.
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListSchemaBundles")
  public func listSchemaBundles(
    byItem: ListSchemaBundlesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<SchemaBundle, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudBigtableAdminV2.ListSchemaBundlesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSchemaBundles(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSchemaBundles(
    parent: Swift.String,
  ) -> any AsyncSequence<SchemaBundle, Swift.Error> {
    let request = ListSchemaBundlesRequest().with {
      $0.parent = parent
    }
    return self.listSchemaBundles(byItem: request)
  }

  public func deleteSchemaBundle(request: DeleteSchemaBundleRequest) async throws {
    try await self.deleteSchemaBundle(request: request, options: .init())
  }

  public func deleteSchemaBundle(
    request: DeleteSchemaBundleRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteSchemaBundle(
    name: Swift.String,
  ) async throws {
    let request = DeleteSchemaBundleRequest().with {
      $0.name = name
    }
    try await self.deleteSchemaBundle(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperations(byItem: byItem, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BigtableTableAdmin_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
