// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A resizable group of nodes in a particular cloud location, capable
/// of serving all [Tables][google.bigtable.admin.v2.Table] in the parent
/// [Instance][google.bigtable.admin.v2.Instance].
///
/// [google.bigtable.admin.v2.Instance]: <doc:Instance>
/// [google.bigtable.admin.v2.Table]: <doc:Table>
public struct Cluster: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The unique name of the cluster. Values are of the form
  /// `projects/{project}/instances/{instance}/clusters/[a-z][-a-z0-9]*`.
  public var name: Swift.String = Swift.String()

  /// Immutable. The location where this cluster's nodes and storage reside. For
  /// best performance, clients should be located as close as possible to this
  /// cluster. Currently only zones are supported, so values should be of the
  /// form `projects/{project}/locations/{zone}`.
  public var location: Swift.String = Swift.String()

  /// Output only. The current state of the cluster.
  public var state: Cluster.State = Cluster.State()

  /// The number of nodes in the cluster. If no value is set,
  /// Cloud Bigtable automatically allocates nodes based on your data footprint
  /// and optimized for 50% storage utilization.
  public var serveNodes: Swift.Int32 = Swift.Int32()

  /// Immutable. The node scaling factor of this cluster.
  public var nodeScalingFactor: Cluster.NodeScalingFactor = Cluster.NodeScalingFactor()

  /// Immutable. The type of storage used by this cluster to serve its
  /// parent instance's tables, unless explicitly overridden.
  public var defaultStorageType: StorageType = StorageType()

  /// Immutable. The encryption configuration for CMEK-protected clusters.
  public var encryptionConfig: Cluster.EncryptionConfig? = nil

  public var config: OneOf_Config? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Cluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Cluster().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let location = CodingKeys(stringValue: "location")
    static let state = CodingKeys(stringValue: "state")
    static let serveNodes = CodingKeys(stringValue: "serveNodes")
    static let nodeScalingFactor = CodingKeys(stringValue: "nodeScalingFactor")
    static let clusterConfig = CodingKeys(stringValue: "clusterConfig")
    static let defaultStorageType = CodingKeys(stringValue: "defaultStorageType")
    static let encryptionConfig = CodingKeys(stringValue: "encryptionConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "location",
      "state",
      "serveNodes",
      "nodeScalingFactor",
      "clusterConfig",
      "defaultStorageType",
      "encryptionConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent(Cluster.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .serveNodes) {
      self.serveNodes = value
    }
    if let value = try container.decodeIfPresent(
      Cluster.NodeScalingFactor.self, forKey: .nodeScalingFactor)
    {
      self.nodeScalingFactor = value
    }
    if let value = try container.decodeIfPresent(StorageType.self, forKey: .defaultStorageType) {
      self.defaultStorageType = value
    }
    self.encryptionConfig = try container.decodeIfPresent(
      Cluster.EncryptionConfig.self, forKey: .encryptionConfig)

    var config: OneOf_Config? = nil
    let configCheckAndSet = {
      if config != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'config'"))
      }
      config = $0
    }
    if let clusterConfig = try container.decodeIfPresent(
      Cluster.ClusterConfig?.self, forKey: .clusterConfig)
    {
      try configCheckAndSet(.clusterConfig(clusterConfig))
    }
    self.config = config
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.serveNodes, forKey: .serveNodes)
    try container.encode(self.nodeScalingFactor, forKey: .nodeScalingFactor)
    try container.encode(self.defaultStorageType, forKey: .defaultStorageType)
    try container.encodeIfPresent(self.encryptionConfig, forKey: .encryptionConfig)

    if let choice = self.config {
      switch choice {
      case .clusterConfig(let value):
        try container.encode(value, forKey: .clusterConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Autoscaling config for a cluster.
  public struct ClusterAutoscalingConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Autoscaling limits for this cluster.
    public var autoscalingLimits: AutoscalingLimits? = nil

    /// Required. Autoscaling targets for this cluster.
    public var autoscalingTargets: AutoscalingTargets? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ClusterAutoscalingConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClusterAutoscalingConfig().with { $0.autoscalingLimits = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let autoscalingLimits = CodingKeys(stringValue: "autoscalingLimits")
      static let autoscalingTargets = CodingKeys(stringValue: "autoscalingTargets")

      static let _knownKeys: Set<Swift.String> = [
        "autoscalingLimits",
        "autoscalingTargets",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.autoscalingLimits = try container.decodeIfPresent(
        AutoscalingLimits.self, forKey: .autoscalingLimits)
      self.autoscalingTargets = try container.decodeIfPresent(
        AutoscalingTargets.self, forKey: .autoscalingTargets)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.autoscalingLimits, forKey: .autoscalingLimits)
      try container.encodeIfPresent(self.autoscalingTargets, forKey: .autoscalingTargets)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.Cluster.ClusterAutoscalingConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for a cluster.
  public struct ClusterConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Autoscaling configuration for this cluster.
    public var clusterAutoscalingConfig: Cluster.ClusterAutoscalingConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ClusterConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ClusterConfig().with { $0.clusterAutoscalingConfig = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clusterAutoscalingConfig = CodingKeys(stringValue: "clusterAutoscalingConfig")

      static let _knownKeys: Set<Swift.String> = [
        "clusterAutoscalingConfig"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clusterAutoscalingConfig = try container.decodeIfPresent(
        Cluster.ClusterAutoscalingConfig.self, forKey: .clusterAutoscalingConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(
        self.clusterAutoscalingConfig, forKey: .clusterAutoscalingConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.Cluster.ClusterConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Cloud Key Management Service (Cloud KMS) settings for a CMEK-protected
  /// cluster.
  public struct EncryptionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Describes the Cloud KMS encryption key that will be used to protect the
    /// destination Bigtable cluster. The requirements for this key are:
    ///  1) The Cloud Bigtable service account associated with the project that
    ///  contains this cluster must be granted the
    ///  `cloudkms.cryptoKeyEncrypterDecrypter` role on the CMEK key.
    ///  2) Only regional keys can be used and the region of the CMEK key must
    ///  match the region of the cluster.
    /// Values are of the form
    /// `projects/{project}/locations/{location}/keyRings/{keyring}/cryptoKeys/{key}`
    public var kmsKeyName: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EncryptionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EncryptionConfig().with { $0.kmsKeyName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let kmsKeyName = CodingKeys(stringValue: "kmsKeyName")

      static let _knownKeys: Set<Swift.String> = [
        "kmsKeyName"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyName) {
        self.kmsKeyName = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.kmsKeyName, forKey: .kmsKeyName)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.bigtable.admin.v2.Cluster.EncryptionConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible states of a cluster.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// The state of the cluster could not be determined.
    case notKnown
    /// The cluster has been successfully created and is ready to serve requests.
    case ready
    /// The cluster is currently being created, and may be destroyed
    /// if the creation process encounters an error.
    /// A cluster may not be able to serve requests while being created.
    case creating
    /// The cluster is currently being resized, and may revert to its previous
    /// node count if the process encounters an error.
    /// A cluster is still capable of serving requests while being resized,
    /// but may exhibit performance as if its number of allocated nodes is
    /// between the starting and requested states.
    case resizing
    /// The cluster has no backing nodes. The data (tables) still
    /// exist, but no operations can be performed on the cluster.
    case disabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .notKnown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .notKnown: return 0
      case .ready: return 1
      case .creating: return 2
      case .resizing: return 3
      case .disabled: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .notKnown: return "STATE_NOT_KNOWN"
      case .ready: return "READY"
      case .creating: return "CREATING"
      case .resizing: return "RESIZING"
      case .disabled: return "DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_NOT_KNOWN": self = .notKnown
      case "READY": self = .ready
      case "CREATING": self = .creating
      case "RESIZING": self = .resizing
      case "DISABLED": self = .disabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .notKnown
      case 1: self = .ready
      case 2: self = .creating
      case 3: self = .resizing
      case 4: self = .disabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .notKnown: return try container.encode("STATE_NOT_KNOWN")
      case .ready: return try container.encode("READY")
      case .creating: return try container.encode("CREATING")
      case .resizing: return try container.encode("RESIZING")
      case .disabled: return try container.encode("DISABLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible node scaling factors of the clusters. Node scaling delivers better
  /// latency and more throughput by removing node boundaries.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum NodeScalingFactor: Codable, Equatable, Sendable {
    /// No node scaling specified. Defaults to NODE_SCALING_FACTOR_1X.
    case unspecified
    /// The cluster is running with a scaling factor of 1.
    case nodeScalingFactor1X
    /// The cluster is running with a scaling factor of 2.
    /// All node count values must be in increments of 2 with this scaling factor
    /// enabled, otherwise an INVALID_ARGUMENT error will be returned.
    case nodeScalingFactor2X
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .nodeScalingFactor1X: return 1
      case .nodeScalingFactor2X: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "NODE_SCALING_FACTOR_UNSPECIFIED"
      case .nodeScalingFactor1X: return "NODE_SCALING_FACTOR_1X"
      case .nodeScalingFactor2X: return "NODE_SCALING_FACTOR_2X"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NodeScalingFactor/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NODE_SCALING_FACTOR_UNSPECIFIED": self = .unspecified
      case "NODE_SCALING_FACTOR_1X": self = .nodeScalingFactor1X
      case "NODE_SCALING_FACTOR_2X": self = .nodeScalingFactor2X
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NodeScalingFactor/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .nodeScalingFactor1X
      case 2: self = .nodeScalingFactor2X
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("NODE_SCALING_FACTOR_UNSPECIFIED")
      case .nodeScalingFactor1X: return try container.encode("NODE_SCALING_FACTOR_1X")
      case .nodeScalingFactor2X: return try container.encode("NODE_SCALING_FACTOR_2X")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum OneOf_Config: Codable, Equatable, Sendable {
    /// Configuration for this cluster.
    indirect case clusterConfig(Cluster.ClusterConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.Cluster"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
