// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for BigtableInstanceAdmin.CreateAppProfile.
public struct CreateAppProfileRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The unique name of the instance in which to create the new app
  /// profile. Values are of the form `projects/{project}/instances/{instance}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The ID to be used when referring to the new app profile within
  /// its instance, e.g., just `myprofile` rather than
  /// `projects/myproject/instances/myinstance/appProfiles/myprofile`.
  public var appProfileId: Swift.String = Swift.String()

  /// Required. The app profile to be created.
  /// Fields marked `OutputOnly` will be ignored.
  public var appProfile: AppProfile? = nil

  /// If true, ignore safety checks when creating the app profile.
  public var ignoreWarnings: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateAppProfileRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAppProfileRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let appProfileId = CodingKeys(stringValue: "appProfileId")
    static let appProfile = CodingKeys(stringValue: "appProfile")
    static let ignoreWarnings = CodingKeys(stringValue: "ignoreWarnings")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "appProfileId",
      "appProfile",
      "ignoreWarnings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .appProfileId) {
      self.appProfileId = value
    }
    self.appProfile = try container.decodeIfPresent(AppProfile.self, forKey: .appProfile)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .ignoreWarnings) {
      self.ignoreWarnings = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.appProfileId, forKey: .appProfileId)
    try container.encodeIfPresent(self.appProfile, forKey: .appProfile)
    try container.encode(self.ignoreWarnings, forKey: .ignoreWarnings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.CreateAppProfileRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
