// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A collection of Bigtable [Tables][google.bigtable.admin.v2.Table] and
/// the resources that serve them.
/// All tables in an instance are served from all
/// [Clusters][google.bigtable.admin.v2.Cluster] in the instance.
///
/// [google.bigtable.admin.v2.Cluster]: <doc:Cluster>
/// [google.bigtable.admin.v2.Table]: <doc:Table>
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The unique name of the instance. Values are of the form
  /// `projects/{project}/instances/[a-z][a-z0-9\\-]+[a-z0-9]`.
  public var name: Swift.String = Swift.String()

  /// Required. The descriptive name for this instance as it appears in UIs.
  /// Can be changed at any time, but should be kept globally unique
  /// to avoid confusion.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The current state of the instance.
  public var state: Instance.State = Instance.State()

  /// The type of the instance. Defaults to `PRODUCTION`.
  public var type: Instance.Type_ = Instance.Type_()

  /// Optional. The edition of the instance. See
  /// [Edition][google.bigtable.admin.v2.Instance.Edition] for details.
  ///
  /// [google.bigtable.admin.v2.Instance.Edition]: <doc:Instance/Edition>
  public var edition: Instance.Edition = Instance.Edition()

  /// Labels are a flexible and lightweight mechanism for organizing cloud
  /// resources into groups that reflect a customer's organizational needs and
  /// deployment strategies. They can be used to filter resources and aggregate
  /// metrics.
  ///
  /// * Label keys must be between 1 and 63 characters long and must conform to
  ///   the regular expression: `[\p{Ll}\p{Lo}][\p{Ll}\p{Lo}\p{N}_-]{0,62}`.
  /// * Label values must be between 0 and 63 characters long and must conform to
  ///   the regular expression: `[\p{Ll}\p{Lo}\p{N}_-]{0,63}`.
  /// * No more than 64 labels can be associated with a given resource.
  /// * Keys and values must both be under 128 bytes.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. A commit timestamp representing when this Instance was
  /// created. For instances created before this field was added (August 2021),
  /// this value is `seconds: 0, nanos: 1`.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool? = nil

  /// Optional. Input only. Immutable. Tag keys/values directly bound to this
  /// resource. For example:
  /// - "123/environment": "production",
  /// - "123/costCenter": "marketing"
  ///
  /// Tags and Labels (above) are both used to bind metadata to resources, with
  /// different use-cases. See
  /// https://cloud.google.com/resource-manager/docs/tags/tags-overview for an
  /// in-depth overview on the difference between tags and labels.
  public var tags: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let state = CodingKeys(stringValue: "state")
    static let type = CodingKeys(stringValue: "type")
    static let edition = CodingKeys(stringValue: "edition")
    static let labels = CodingKeys(stringValue: "labels")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let satisfiesPzi = CodingKeys(stringValue: "satisfiesPzi")
    static let tags = CodingKeys(stringValue: "tags")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "state",
      "type",
      "edition",
      "labels",
      "createTime",
      "satisfiesPzs",
      "satisfiesPzi",
      "tags",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Instance.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Instance.Type_.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Instance.Edition.self, forKey: .edition) {
      self.edition = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.satisfiesPzs = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs)
    self.satisfiesPzi = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.edition, forKey: .edition)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encodeIfPresent(self.satisfiesPzi, forKey: .satisfiesPzi)
    try container.encode(self.tags, forKey: .tags)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Possible states of an instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// The state of the instance could not be determined.
    case notKnown
    /// The instance has been successfully created and can serve requests
    /// to its tables.
    case ready
    /// The instance is currently being created, and may be destroyed
    /// if the creation process encounters an error.
    case creating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .notKnown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .notKnown: return 0
      case .ready: return 1
      case .creating: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .notKnown: return "STATE_NOT_KNOWN"
      case .ready: return "READY"
      case .creating: return "CREATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_NOT_KNOWN": self = .notKnown
      case "READY": self = .ready
      case "CREATING": self = .creating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .notKnown
      case 1: self = .ready
      case 2: self = .creating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .notKnown: return try container.encode("STATE_NOT_KNOWN")
      case .ready: return try container.encode("READY")
      case .creating: return try container.encode("CREATING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type of the instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Hashable, Sendable {
    /// The type of the instance is unspecified. If set when creating an
    /// instance, a `PRODUCTION` instance will be created. If set when updating
    /// an instance, the type will be left unchanged.
    case unspecified
    /// An instance meant for production use. `serve_nodes` must be set
    /// on the cluster.
    case production
    /// DEPRECATED: Prefer PRODUCTION for all use cases, as it no longer enforces
    /// a higher minimum node count than DEVELOPMENT.
    case development
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .production: return 1
      case .development: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .production: return "PRODUCTION"
      case .development: return "DEVELOPMENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "PRODUCTION": self = .production
      case "DEVELOPMENT": self = .development
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .production
      case 2: self = .development
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .production: return try container.encode("PRODUCTION")
      case .development: return try container.encode("DEVELOPMENT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible editions of an instance.
  ///
  /// An edition is a specific tier of Cloud Bigtable. Each edition is tailored
  /// to different customer needs. Higher tiers offer more features and better
  /// performance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Edition: Codable, Equatable, Hashable, Sendable {
    /// The edition is unspecified. This is treated as `ENTERPRISE`.
    case unspecified
    /// The Enterprise edition. This is the default offering that is designed to
    /// meet the needs of most enterprise workloads.
    case enterprise
    /// The Enterprise Plus edition. This is a premium tier that is designed for
    /// demanding, multi-tenant workloads requiring the highest levels of
    /// performance, scale, and global availability.
    ///
    /// The nodes in the Enterprise Plus tier come at a higher cost than the
    /// Enterprise tier. Any Enterprise Plus features must be disabled before
    /// downgrading to Enterprise.
    case enterprisePlus
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enterprise: return 1
      case .enterprisePlus: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EDITION_UNSPECIFIED"
      case .enterprise: return "ENTERPRISE"
      case .enterprisePlus: return "ENTERPRISE_PLUS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Edition/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EDITION_UNSPECIFIED": self = .unspecified
      case "ENTERPRISE": self = .enterprise
      case "ENTERPRISE_PLUS": self = .enterprisePlus
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Edition/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enterprise
      case 2: self = .enterprisePlus
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("EDITION_UNSPECIFIED")
      case .enterprise: return try container.encode("ENTERPRISE")
      case .enterprisePlus: return try container.encode("ENTERPRISE_PLUS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.Instance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
