// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A materialized view object that can be referenced in SQL queries.
public struct MaterializedView: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The unique name of the materialized view.
  /// Format:
  /// `projects/{project}/instances/{instance}/materializedViews/{materialized_view}`
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. The materialized view's select query.
  public var query: Swift.String = Swift.String()

  /// Optional. The etag for this materialized view.
  /// This may be sent on update requests to ensure that the client has an
  /// up-to-date value before proceeding. The server returns an ABORTED error on
  /// a mismatched etag.
  public var etag: Swift.String = Swift.String()

  /// Set to true to make the MaterializedView protected against deletion.
  public var deletionProtection: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MaterializedView`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MaterializedView().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let query = CodingKeys(stringValue: "query")
    static let etag = CodingKeys(stringValue: "etag")
    static let deletionProtection = CodingKeys(stringValue: "deletionProtection")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "query",
      "etag",
      "deletionProtection",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .query) {
      self.query = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .deletionProtection) {
      self.deletionProtection = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.query, forKey: .query)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.deletionProtection, forKey: .deletionProtection)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.MaterializedView"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
