// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A snapshot of a table at a particular time. A snapshot can be used as a
/// checkpoint for data restoration or a data source for a new table.
///
/// Note: This is a private alpha release of Cloud Bigtable snapshots. This
/// feature is not currently available to most Cloud Bigtable customers. This
/// feature might be changed in backward-incompatible ways and is not recommended
/// for production use. It is not subject to any SLA or deprecation policy.
public struct Snapshot: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The unique name of the snapshot.
  /// Values are of the form
  /// `projects/{project}/instances/{instance}/clusters/{cluster}/snapshots/{snapshot}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The source table at the time the snapshot was taken.
  public var sourceTable: Table? = nil

  /// Output only. The size of the data in the source table at the time the
  /// snapshot was taken. In some cases, this value may be computed
  /// asynchronously via a background process and a placeholder of 0 will be used
  /// in the meantime.
  public var dataSizeBytes: Swift.Int64 = Swift.Int64()

  /// Output only. The time when the snapshot is created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// The time when the snapshot will be deleted. The maximum amount of time a
  /// snapshot can stay active is 365 days. If 'ttl' is not specified,
  /// the default maximum of 365 days will be used.
  public var deleteTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The current state of the snapshot.
  public var state: Snapshot.State = Snapshot.State()

  /// Description of the snapshot.
  public var description: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Snapshot`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Snapshot().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let sourceTable = CodingKeys(stringValue: "sourceTable")
    static let dataSizeBytes = CodingKeys(stringValue: "dataSizeBytes")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let state = CodingKeys(stringValue: "state")
    static let description = CodingKeys(stringValue: "description")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "sourceTable",
      "dataSizeBytes",
      "createTime",
      "deleteTime",
      "state",
      "description",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.sourceTable = try container.decodeIfPresent(Table.self, forKey: .sourceTable)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .dataSizeBytes) {
      self.dataSizeBytes = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent(Snapshot.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.sourceTable, forKey: .sourceTable)
    try container.encode(self.dataSizeBytes, forKey: .dataSizeBytes)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.description, forKey: .description)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Possible states of a snapshot.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// The state of the snapshot could not be determined.
    case notKnown
    /// The snapshot has been successfully created and can serve all requests.
    case ready
    /// The snapshot is currently being created, and may be destroyed if the
    /// creation process encounters an error. A snapshot may not be restored to a
    /// table while it is being created.
    case creating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .notKnown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .notKnown: return 0
      case .ready: return 1
      case .creating: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .notKnown: return "STATE_NOT_KNOWN"
      case .ready: return "READY"
      case .creating: return "CREATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_NOT_KNOWN": self = .notKnown
      case "READY": self = .ready
      case "CREATING": self = .creating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .notKnown
      case 1: self = .ready
      case 2: self = .creating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .notKnown: return try container.encode("STATE_NOT_KNOWN")
      case .ready: return try container.encode("READY")
      case .creating: return try container.encode("CREATING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.bigtable.admin.v2.Snapshot"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
